---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./cilium-ip-pools.yaml
- ./cilium-l2-advertisement-policy.yaml
- ./ipv6-pool-reconciler-rbac.yaml
- ./ipv6-pool-reconciler-cronjob.yaml
configMapGenerator:
- name: cilium-values
  namespace: kube-system
  files:
  - values.yaml=values.yaml
  options:
    disableNameSuffixHash: true
    labels:
      reconcile.fluxcd.io/watch: Enabled
- name: ipv6-pool-reconciler-script
  namespace: kube-system
  files:
  - reconcile.py=ipv6-pool-reconciler.py
