apiVersion: apps/v1
kind: Deployment
metadata:
  name: siyuan
  labels:
    app: siyuan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siyuan
  template:
    metadata:
      labels:
        app: siyuan
    spec:
      containers:
        - name: siyuan
          image: b3log/siyuan:v3.6.5@sha256:1a316554bfbf0c951ddabc7d3cb0292620152b44c087b6979d5d9b6bae065b1b
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6806
          env:
            - name: TZ
              value: "Asia/Shanghai"
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: siyuan-workspace
              mountPath: /siyuan/workspace
      volumes:
        - name: siyuan-workspace
          persistentVolumeClaim:
            claimName: siyuan-workspace-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: siyuan
  labels:
    app: siyuan
spec:
  selector:
    app: siyuan
  ports:
    - name: http
      port: 6806
      targetPort: 6806
