apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: siyuan-workspace-pvc
  labels:
    app: siyuan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 10Gi
