apiVersion: v1
kind: Secret
metadata:
  name: siyuan-secret
type: Opaque
stringData:
  SIYUAN_ACCESS_AUTH_CODE: ENC[AES256_GCM,data:rC/fvIQBg7uC0/Ih,iv:etL2AMXNHdk1CPy6+4OArVl+eXq2psBdmJAeDceFu04=,tag:bTOIpr9EtBaniCj8YKEcow==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaV1gyS0I2WjJKUFNxY1hE
        RncxMWw0VGNTOGl5MkdCa0NZUjlSdkZhUFJJCm9QV2kySGZhSWhmeGlsL1F1MU56
        SjF5WlNpUmNDY0dDYkdZb1FDYytXQmcKLS0tIFNzaDYzYlQ3aFVsdlVqdlRKaVRs
        YitNSW42UTJNbFprZStudnVnSTZUbjAKY2pUKtptf/OYaxoIyLmExrQTyce5kGcz
        Jxb5TSuhloQZrMR3pYk7xVpXmsDaIIT6Slu7P7keZ08TuV9u3ehJ1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-14T14:20:38Z"
  mac: ENC[AES256_GCM,data:rmM3bTNZvA5AMFWPBbYHqs5i+h+ePLQ/n5haJ2GUk01oJOGsybO0EJPbjxv2ZkxImwFmyEdAyuBZQm+dVs9aU1vTChotwHxbuaOHHRhBWxSWuv47S8khM5gb626GTedjYAeITmKDEcm2EhuO1ztAbFiVDg8yYHJsDlcF4kP8iDk=,iv:MV0cSF7yrxKAi5nuU1AO5Pon5jZ2ZXMHDIUa50lw1y4=,tag:7r06Yex4BLsyZFb11UD52w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
