apiVersion: v1
kind: Secret
metadata:
  name: default-tunnel-secret
  namespace: cloudflare-operator-system
type: Opaque
stringData:
  CLOUDFLARE_TUNNEL_CREDENTIAL_FILE: ENC[AES256_GCM,data:e4deQbGGnT+MmtlRjigMX7uTihBgBmFlWvgWHT2X6IpTIrjwFQHhi4BGUS/n8Ti/r58yjI6po/hK4pUvEOknk8RTDg3B6RGdesw7wOXVWZqCUGN33zYjfxeNnklpaXNeQ1aDxHPMyta9KMCrwO99PG1DUwkX/pTOkJC40yhxPIOwntTdlJniwIqmCNCprSKEQNqkPQcllp1t7ksok/VivkojKVDHLmWBuKfJ6MZj1jqxf+PO9v2dsJi/ctcaxqB0g5zIUe8O,iv:n9MsKdCKb0t04nfEW7kswH+C9FiZv/lOoUyMvwH/UtA=,tag:K6Pvn6f5K242RhKrRknu3A==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMEVrSDQ1ak55VUtzR2d5
        ZmVnT1h2SGptUHkyOW40eE9RTkhXdWMzSzIwCk9NWjBwdzMyMVhpdkRPMHVGd0FS
        akREWGRIM0tESUFaK2lZeEM1VzhJRG8KLS0tIElSRWF4dUk0bHllTllpanZSY216
        ckZvbk0zSTVOTnVNQlZlVytmY2xabEkKQgd2c3yJ2s/sXzRlvrR8zNRLW+BXHr4p
        1T+FMt6kT4UVaVDkspwF7d6tPtHLftHeoZmWdqwSzvm7BHX3Lex+Vg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-21T14:56:41Z"
  mac: ENC[AES256_GCM,data:ooYDr/UiL2mf2KtmPEvXADEz9tQBo3FNLrMi6E6vA6Ul//bqm0zR2AHCh9jOICYt3JjyYBXtZ9sodUyH5roxsHrdlqBk1ySucsSphpWhGaJuuBncGVDfecW1qlzTWaorZ0vhFJiDh3B2P1h/yDKqgdpOx4xqzEVS7TDja59eWJM=,iv:4TF8tpxbDkhwtIVJq41uHdK1y5pJ8pdBUb/RxUkeJyw=,tag:Frdf/qQ1i1I/XcrJtTr+cQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
