---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    app.kubernetes.io/version: v1
    dashboards: grafana
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  client:
    useKubeAuth: true
  config:
    server:
      root_url: https://grafana.isning.moe
      enable_gzip: 'true'
    log:
      mode: console
    auth:
      disable_login_form: 'true'
    auth.generic_oauth:
      enabled: 'true'
      name: Logto ISNing
      allow_sign_up: 'true'
      client_id: $__env{AUTH_CLIENT_ID}
      client_secret: $__env{AUTH_CLIENT_SECRET}
      scopes: openid email profile offline_access roles
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: name
      groups_attribute_path: groups
      use_refresh_token: 'true'
      auth_url: https://logto.isning.moe/oidc/auth
      token_url: https://logto.isning.moe/oidc/token
      api_url: https://logto.isning.moe/oidc/me
      allow_assign_grafana_admin: 'true'
      role_attribute_path: contains(roles[*], 'grafana:instance_admin') && 'GrafanaAdmin' || contains(roles[*],
        'grafana:admin') && 'Admin' || contains(roles[*], 'grafana:editor') && 'Editor' || contains(roles[*],
        'grafana:viewer') && 'Viewer' || 'None'
      validate_id_token: 'true'
      jwk_set_url: https://logto.isning.moe/oidc/jwks
      signout_redirect_url: https://logto.isning.moe/oidc/session/end?post_logout_redirect_uri=https://grafana.isning.moe/login
    auth.jwt:
      enabled: 'true'
      header_name: Authorization
      expect_claims: '{"aud": ["grafana.isning.moe"]}'
      username_claim: sub
      email_claim: sub
      auto_sign_up: 'true'
      role_attribute_strict: 'true'
      role_attribute_path: contains(sub, 'system:serviceaccount:kiali-operator:kiali-service-account')
        && 'Viewer' || 'None'
      jwk_set_url: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT_HTTPS}/openid/v1/jwks
      jwk_set_bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_client_ca: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  disableDefaultAdminSecret: true
  deployment:
    spec:
      template:
        metadata:
          labels:
            app: grafana
            app.kubernetes.io/version: v1
        spec:
          containers:
          - name: grafana
            env:
            - name: AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: grafana-managed-oidc
                  key: clientId
            - name: AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: grafana-managed-oidc
                  key: clientSecret
  httpRoute:
    spec:
      parentRefs:
      - name: default-gateway
      hostnames:
      - grafana.isning.moe
      rules:
      - backendRefs:
        - name: grafana-service
          port: 3000
