apiVersion: v1
kind: Secret
metadata:
  name: harbor-oidc
  namespace: harbor
type: Opaque
# This key is merged into Helm values via spec.valuesFrom.valuesKey.
# Keep configureUserSettings as a single-line JSON string value.
#   overrides.json: '{"self_registration": false,"auth_mode": "oidc_auth","primary_auth_mode": true,"oidc_name": "ISNing","oidc_endpoint": "https://logto.isning.moe/oidc","oidc_scope": "openid,profile,email,roles,offline_access","oidc_client_id": "534gp0torf1s2dsokwcwo","oidc_client_secret": "[REDACTED]","oidc_verify_cert": true,"oidc_auto_onboard": true,"oidc_user_claim": "username","oidc_groups_claim": "roles","oidc_group_filter": "^harbor:[a-z]+$","oidc_admin_group": "harbor:admin","oidc_logout": true}'
stringData:
  overrides.json: ENC[AES256_GCM,data:9kpkMpc0XLu1sJ8EN3wgJJF4o8OrbnMPyX98SCpjeTybMo7htFMq5EeX1UOPsUo9iN8RxmAtxlmhTLNk7GmNtcIop//iUzy4WSo9nkiJGL6SRB41AX5Z8kBFMIMP7PbdK6v/qVArPbSS3GomHT4GRwTbXFTh3isHY4JX+hJrXGXWwWOTVt5NG3TSO8qpHvw0oWUWjS+FGWwoLGbfryxQ+rzQlPfu3E+GHP7zTgpIg222Rg/mJo5UfN/pcsA2ChFwwC4zLK6VLDIr9DjfoyC1vHaRFT2H/v1ztCwq19n4x+kdi36QB+4eve+7ObZQX+R1a5dv9tSE8H7iskIKQFkfhoAZOCA4HH3PlhslngJROXFSn3L8m2B0g9u0IyhcW7mGu2W8CoIQHLj9d1NMWp8MLDZ79W5JUiXKW0lki+ZQxm/vaIgpM7xNKTlVM10AH7T9QPX+k6OvcR7CqJXwUfh++tDT0naPiSmd53VxZ2QGVeepQGgFkBVKb7vcKn1Zd1nmmRuQot28mY3Mfufb97VrMZF+Hkbvb176/LdLEy4vXWaamYzzFcAOm6cWyNdngJM2KS8yXdBJgoLeTJzZMLNUCounozYmLxIPdL32POcukh+gAJR7KQhGITqOkr9slMC6QvmQ+mXdQW3ryM8yiTFqEo4CtlwVt0EFy8waxr6AkQ==,iv:N5eapX4A+AJdkDaCYyAc62RiRXYFMoVRhdq95gWusCM=,tag:NSkRQmfJZiT/ePCjiDsVwg==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeDR5K00rWEdleTRmVjla
        SjErdDN0bW0xOVdaVGxPZWxQQUFNU01UaURvCnRaUUFUNDJBNXp4WjAxcFhUN1FU
        SVpuTG1hUGQxWFhJWmUwa0gxVjNYTlEKLS0tIDRLSWJ2UzJtMUkwWjdTZ0VCaU16
        ZWpwcUx0OVltSy92NTB6SVRTOElMalUKqbhi1gjQXz2SV4g+6aIic0tI4MmjGLUG
        2RBBLrC9VMPGYAGrBgr3swAkns74vSkOubEk8M1j/oSOJKTz4OLHzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-15T06:23:27Z"
  mac: ENC[AES256_GCM,data:FwDyzyzKxLzZn18tRKMcZfe9QzwUaCaN4Fss/+QVT7qPHXCIdtMVVOu8gXpGN5BhPbdIXjB+5DqLPPQ0SdJrS9RqInsPFIjavEXcp1nA4033i19YYov+1I9M3Js/kQ9XVlBsptzlLWsIhfVGZES7eaq3WK1iaemcAzv1pocpVc0=,iv:pZ3xGwilsxVUNFCuJJ/9Gn77kQc0Y+r0H98vllW5BeQ=,tag:c2vYzwefRsTErsTXts1JcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
