apiVersion: v1
kind: Secret
metadata:
  name: harbor-admin-auth
  namespace: harbor
type: Opaque
stringData:
  HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:oRJx9wJk/WSbgqTMMacxvODmP2z0v4Mg,iv:pDejiBU4RNuGNbp2Hj92MF5I58Hdtwbvz0VziJUvKnQ=,tag:5x6sZ2Z0LOh3nWRYItJMnw==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacmpieE5tZUl6cDRoZFRD
        RGpFYW9tVEJGbzZMMEFvZXRmUTNsRzA0LzFjCjM3MzBCUGNUQm1sdU9yOUIrNGlC
        TlpmOVBDaFZCWE1IUHppZDlVWmpaRzQKLS0tIHRxTjJnTGYxTkIxaGZ5R1RkV3c1
        RlU2TUczWW5MR1NJVFUyK1VzdUE5b2MK0OdIN/aR4MB/nRxEWHOHk9SXfMvOsgNz
        fhgZI3GPnlbajCoQMbmXWaGaXzVzZu3dJG2z2f1SilxOD3EkxRdMnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T14:39:53Z"
  mac: ENC[AES256_GCM,data:IQATksfbEPs1bKHs1qdwr2JNSO1FeYYrhozOraYoWClejLNMaQnN/hp35J0rfOCvMkHofAePF/4pFLS4Jm4JTwGU6W8mhwiA9DryrjFRgUWUAiPdus+WcZsc79Y40Dw5r0o1psgEI5TWvwXulBp+vs1QnrZ/7PEO4ARcTMbzDbU=,iv:ZnrsvQbwO5BSLMRjPdX3661jEdpsRZnt7rkUUU3/nO4=,tag:fIybcDepvZS3qCTy3Ey+9A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
