apiVersion: v1
kind: Secret
metadata:
  name: harbor-redis-auth
  namespace: harbor
type: Opaque
stringData:
  REDIS_PASSWORD: ENC[AES256_GCM,data:IejVfyagxBs8y98PdbaQO3bTZtg9v59s,iv:zbV+3LGgND9jVFrSgsWTtgEGVJ46Jcd1W/GVZGsuAx4=,tag:FbYGKCrTkhQjwIdmBP0KEg==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUE04MWw4ajBrenRJblRS
        cHdMazN1YytpU2FMQ0tkTFZYei9Dc1M0OGt3CmwyckRWZUE0STg1M1VPeEN0dyt5
        UDBzZlJRNnJsQXhhOVNQM2FtdFNyZXMKLS0tIHVha0IvR09tOXdsdmk5SndIM1Zu
        am1DWE1TbHZjenJYVStTZE5uNnA4S2MKq4uLEQjaOCPKG+JG9P3HXSv8Jj/Mpukf
        42OtrXTK7SAhdMuCcsl5ns1MfxHe7nP9YLtedeK4B8IddKDSRnaBsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-10T06:47:17Z"
  mac: ENC[AES256_GCM,data:HgSy8jPXylZcoflS04bxHF/wNr0TLxBqW6d3u2Lxgmdk7BPzLPngmE3MLMOYcQM0tezJh9UqYYRYRwBgaMM9mURNtaOfSy19C3ia0hnAUJKOf+r/Y6C/JveNmgDbei4iU+DUmnRzKA522HSevM+B8hii7nFISkMbrSz/lBNNmYE=,iv:gytDNWXawYCRtP7pDog6FC+aSoph7Dh30TL+n58vjyU=,tag:VCIAmV/Ix4K973L3jco2GA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
