apiVersion: v1
kind: Secret
metadata:
  name: harbor-redis-auth
  namespace: harbor
type: Opaque
stringData:
  redis-password: ENC[AES256_GCM,data:9p8whqq3CGcGP/DlkGY1fGaS59zFz918,iv:aXzY73a6Rupl31XJXDGBAKBPNYPhzs8X/XA0fPbNlJE=,tag:HPdeL7lYqxLSWwP3HFkQdA==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UlhqSzd3aDhVa1NhOHFa
        bWlVcWlhOGZPZXpZaVdPZEhrZnlXUXQ5RDNzCmN3eStHTm9wZGt1a0c4VDg1N0pI
        YzI1WjBFSTVITEo5cG52VTQvMzZwRUUKLS0tIDA5cEZmb3NFLzhFMTZCVllPVGlt
        Q2dwcVI1dlhrZUM2QmhGSDRkQVowbzQKM0iBCt0q514Yz1TZSP/QlRHNYxPlahjU
        crydL1LvWdpKnJ5lsePUXJVD0IcwpW/+KEPI7bkXeT3m8+n1cvpYzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-15T07:01:15Z"
  mac: ENC[AES256_GCM,data:HgtxHdpV2qrpb+6nPwYjFCkW9JPQ78QqdfoDZ8m5cmMJcAWgE92SPQhmujcLsKEipdb3sXOJxLCQYIaTJ0fudsO8q2B6wOT4rWz/4tbh/ysOMxnWHJCJpiQcv+Vs1dawqIfLmerhYMwRh/lX04SCSugOfv6fJl+n6dkgNiAlLSQ=,iv:P1l3YU1/VeGrnNNCQEwKUbRnBG3rTvlKivUKS6wpwAA=,tag:LUg52Qzos7oiMfAtSzyC/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
