apiVersion: v1
kind: Secret
metadata:
  name: harbor-oidc
  namespace: harbor
type: Opaque
# MUST be a single line json string, otherwise harbor will fail to parse it
# https://goharbor.io/docs/latest/install-config/configure-system-settings-cli/#set-configuration-items-using-an-environment-variable
#   configure-user-settings-json: '{"self_registration": false,"auth_mode": "oidc_auth","primary_auth_mode": true,"oidc_name": "ISNing","oidc_endpoint": "https://logto.isning.moe/oidc","oidc_scope": "openid,profile,email,roles,offline_access","oidc_client_id": "534gp0torf1s2dsokwcwo","oidc_client_secret": "[REDACTED]","oidc_verify_cert": true,"oidc_auto_onboard": true,"oidc_user_claim": "username","oidc_groups_claim": "roles","oidc_group_filter": "^harbor:[a-z]+$","oidc_admin_group": "harbor:admin","oidc_logout": true}'
stringData:
  configure-user-settings-json: ENC[AES256_GCM,data:23Cz9/NyEUmt+yrtjPVaFLVUxm1bXFM+yWK+QyC9kmSgarNUDWPXVRQN95jSuGr9mJiSPibZ2PJyHkcCaBodxyXTD4knSuh2tg/KPK179CGf18LMVlcW9ritZwjX7hE8kQmFyjY1kSnNwvmU3gJ5qSiTInpCxiyIJWvK8OKA+iAb0j4IbqK3AHoOFGTlwckoetrDEXpmtwjzR1q+GrQCfQnED9r6rMmtF4rNGEjz52ec24xGekHaXlpO3C877F4nB2VDqt2RBToX2idxhcP582Efac0NGMfy4jX06vx0rCtNJUmXy1MiBdY03qioOKEhBmmZa990P+yTlGSSE8CspqrpiKGBgZ8Xhbp8guV+2Vt7i4E3Nq1w+ydYlHnR0AWU1BUcU9OBjWsdpr7wCPXW6x5ubOGJ+c32Ud3DZ6P1JvxzFkKMXRKHDM54vpV8ti0Ci0qvSQewvzsfbJu1YuUaJZpCgykCkHLXZjf3knBuBeJ3O558E/uxJScL/ejwUzXIWSBxxeCihE/kqA8y2+YMbX7ON1PSHW70J76mO0qyga/8vq2rdAA9teeeph8pEg6p8gr7TNaliMImmpE89n7Zz0Xci4awBEZu4l2Jq7nPy4KwHv5/SWd8Ts60DFxPsE0NalFmAmyb1aKdu/U6Qu4/JgZgSEtaCQ9ikZhM4PLndQ==,iv:rJFkkxFpJ9H2xpLe/47MdWrpOWR3/rS8QrtJEHCVnLM=,tag:fDMAVHm5G1kNR3gFBJ80hg==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aE5FRUliY3JlUzFJUTQy
        K2N3QmlkeDBuY29aSmFLM1p3L01ZQ0ZnSEJFCk5BUUpnTVkrNGk5YUgyRkxha3NC
        cXZqc2F2T0xZMnBIM2FKKzB6aFl5VW8KLS0tIGRtNzdqNXBUcmVRbVlWTFgyZk8z
        anowRndvWFVzdVQvbmVyK2FmdXhZdVEKSngXrcMiovdswNfFmwbN8j84Xpo+sRzk
        EifRsSmvFRnKVXpcGyy8RZf037TKw3aaBn1CDlAmI/byquzPKxgS2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T18:18:46Z"
  mac: ENC[AES256_GCM,data:wbfXMUpC8CAiI7Uh3HdwArWG7VQpcMmWtSqmuYXiSYBrZQBUyAj09MM+8qe06sYs94jinC+cMFt9sOXNktBvKOUV9PYtWW8spCaA0yCpYJBapOwZhw6g86ublPhxBHz7z9jAhIBTNNZCQY7ewF/gpOUM/Tmgg0g3MYxz/4Qcq3U=,iv:R+CykD9Stau8pZun6BH7DNSZF/AMQvjW/P+JO3RJvbE=,tag:yuhXVZsrblQEfl5b5hpiHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
