apiVersion: v1
kind: Secret
metadata:
  name: harbor-oidc
  namespace: harbor
type: Opaque
stringData:
  configure-user-settings-json: ENC[AES256_GCM,data:MI7luK7JEfRxC+mlVGVTGI3k/EJDZBuCv6pWAKtwdBHmqX1RUYeP+rqUfqm7Thrf8KPiLU+mbd0+ffnzDi3V1xCH94QCIOxmVNqqGoVNV+jDbr3O5FyfTDZuP3/OEHN8fvBKFtrlEGWWa9qzHoqjYsKT5sWztdYrZnpIx9Z0dz+bE9M+IOozaViBidZYXdbSNik6U8m3zytM0mHCaz+Ul0Qf9aK3mwtDOLwBsZ+TU/ZtcfP7UUqO4Yt46++/iiGgcr4einfqPAXbZSqjl4RiscjzfsL6oFnmFCI661cQ8U2aiqhcvxciMEhV5Pt2u8i3c1dP1Ol1e/DiW27p3weUp3Z9YUvrPxNwyYFaE/FhCDFQ6Ec/LLzCoVlVtiLXNsIZdRC5Lp9LcchR2TofkD9bfp6iO4CX9+RTob/h3eo1lexw2JptN/eRykDq3WAwDGCPoQL6wppwpakF3pyp6r2nebY8KowQjNPg5ks8BRDOrr5RgFc7YW8kwOV90UB/eLHnz1DLZUg+VQuIMlEWWNN/Xfxv4N2ohDs4ubsKohSUO5uuNQdkOi1La5sUiooyq/FU/aR10WxK2Db/tntvmrgECmxjS+rWbPI4ECgs6nw50mA1M6PjCRiEHdu/6eiJvO9Ua9DJJmjYNePJUvtO+wXvv7+g0gQkg+NEsmt584KcTXVYh1X/gNniN2MZfG5rdJfb,iv:kGJGx6mTaqIJ0fD1nUwI3GBe7+YM856SjZbZk9OrsSQ=,tag:A+JUPPKWkb/mBcqqYuFLhg==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVU1sR0JjaC8venVibE1a
        NmZXRmR4am1NZ1VMMFNGazMwTkRFQy9VVWxRCmN0MFlNRloyT0ZJdkQ5OUM1SlZL
        anI0KzNNNHZhRE5UZmpHTDA4cWlCKzAKLS0tIFNWZXh1ZW1NM052KzI2UkcrdVpS
        bUs5dmg0QnZKSWFDMUY0bFhtdGhicUEKae4cY0RW3soJ/kuVjAaA6Pm/dq6Ouz4h
        GcXdyzZQkwZVpPZLJTFHybCGzbJZNS3VZN8d90AhzZ7vqkiSUpNmgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T14:42:28Z"
  mac: ENC[AES256_GCM,data:hAgvX1FLSdvJulr8EJzZyk7ZYvN/clqjLuzxA2dc3nVMNaj7zY7htjVxKt8+RkZVM6tZoCQw2yy90LVje+Hfv8Gxj6KYW+jVng8caKq3G3M/1osaiV2rpcTMX7rVE2m5luuShL787oN+I4VUInyYZwFhEsO1e1dBXQ9Pf2vBByE=,iv:sLP27bsZJvUQjPNHdsnofhBCwzydDndNPFjay+xuVkc=,tag:9XSM2p9E9GHoZsTfApeSNw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
