# Vaultwarden Admin Token Secret
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-admin
type: Opaque
stringData:
  admin-token: ENC[AES256_GCM,data:vf3fLdhfztdkQAtOsZ3w6Q==,iv:flhbPVJM3HQz6GK/WN+y+omqSiljVykSeJK5OjQN+pk=,tag:IXWcKEBKBnW5+hTvW7X5Cg==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaWhaL293Y3BXQ2VHTHMr
        UEVKZ2tFYlJyejZoL1Q5ZGJDc3dZOFdWMmlrCi9UTWhZSmNQa1hyclp2bGVUUHRK
        M3g4MitCU1ZBZFNBN2U0b1RLRDBJRHMKLS0tIGZ0amJYOGZZQ3JjazVyRXc5TzJQ
        VHJpNWFsY2FPb3d0TGErcHBWd2FVM28Kbd6XbWiEKTFmYzYG3sPd/p28Udf3v6GD
        +hIf3e4Vqb/kChrSqYbpo/YCQzvIl5Jy3IuTWb/g9OUeprpD0S3R2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-17T14:03:22Z"
  mac: ENC[AES256_GCM,data:kdTctmTjxq5GVTLAVCTOj6p8orZlFxumgJfr5voWqZfJBZeDjRR8RKZ/DISaJfRG8YKTreZv5mJChTvZbnoRKqsxMnRBaIpR5z15Na/+L18EmpwlqXgO84bnbshfu9J33XTNI/E7QsKBroKk7Qq2hJTIZ73evXjTnMeiSAjgQCU=,iv:uMACNO/divpeSz8KIuOfBkV+yiedfYgDLmbNfsSOTvo=,tag:DCR6bTBem7+WbnDSQO6icg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
# Vaultwarden SMTP Credentials
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-smtp
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:ewS3OisEPl1+CK+c3jfaOg==,iv:+e7XHIOtQME2aWHUuUfs6ijNzbAuoquPJ9jHu8AFAsI=,tag:/kC2wLbzxPUn8jGeIGFpeA==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaWhaL293Y3BXQ2VHTHMr
        UEVKZ2tFYlJyejZoL1Q5ZGJDc3dZOFdWMmlrCi9UTWhZSmNQa1hyclp2bGVUUHRK
        M3g4MitCU1ZBZFNBN2U0b1RLRDBJRHMKLS0tIGZ0amJYOGZZQ3JjazVyRXc5TzJQ
        VHJpNWFsY2FPb3d0TGErcHBWd2FVM28Kbd6XbWiEKTFmYzYG3sPd/p28Udf3v6GD
        +hIf3e4Vqb/kChrSqYbpo/YCQzvIl5Jy3IuTWb/g9OUeprpD0S3R2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-17T14:03:22Z"
  mac: ENC[AES256_GCM,data:kdTctmTjxq5GVTLAVCTOj6p8orZlFxumgJfr5voWqZfJBZeDjRR8RKZ/DISaJfRG8YKTreZv5mJChTvZbnoRKqsxMnRBaIpR5z15Na/+L18EmpwlqXgO84bnbshfu9J33XTNI/E7QsKBroKk7Qq2hJTIZ73evXjTnMeiSAjgQCU=,iv:uMACNO/divpeSz8KIuOfBkV+yiedfYgDLmbNfsSOTvo=,tag:DCR6bTBem7+WbnDSQO6icg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
# Vaultwarden R2 Backup Credentials
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-r2-credentials
type: Opaque
stringData:
  access-key: ENC[AES256_GCM,data:Ww+WYshsTBZmt3yUdCH3XvWXiyLtr9+Eaaz6HCQVh/Y=,iv:f6Gdds2SMQ2clJVwehDGQvgdeZWIZfVN0D/sAxAwtFU=,tag:MApIscyQOAAVv1SUNGvVgA==,type:str]
  secret-key: ENC[AES256_GCM,data:KTSWpAal1pOi9DzNEvo4NV0IJXFdv1ql5if8Mf/Yi7IIwEwRxpdQPOrNdyk84DHyWV8lrd8rtParlQMinOPgYg==,iv:hxfM0X0AslmdwtacTDRy+wMwjkdXqMUjdaDtJOUjkR4=,tag:q0QQ+xzhKpi1G7BkyucF4A==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaWhaL293Y3BXQ2VHTHMr
        UEVKZ2tFYlJyejZoL1Q5ZGJDc3dZOFdWMmlrCi9UTWhZSmNQa1hyclp2bGVUUHRK
        M3g4MitCU1ZBZFNBN2U0b1RLRDBJRHMKLS0tIGZ0amJYOGZZQ3JjazVyRXc5TzJQ
        VHJpNWFsY2FPb3d0TGErcHBWd2FVM28Kbd6XbWiEKTFmYzYG3sPd/p28Udf3v6GD
        +hIf3e4Vqb/kChrSqYbpo/YCQzvIl5Jy3IuTWb/g9OUeprpD0S3R2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-17T14:03:22Z"
  mac: ENC[AES256_GCM,data:kdTctmTjxq5GVTLAVCTOj6p8orZlFxumgJfr5voWqZfJBZeDjRR8RKZ/DISaJfRG8YKTreZv5mJChTvZbnoRKqsxMnRBaIpR5z15Na/+L18EmpwlqXgO84bnbshfu9J33XTNI/E7QsKBroKk7Qq2hJTIZ73evXjTnMeiSAjgQCU=,iv:uMACNO/divpeSz8KIuOfBkV+yiedfYgDLmbNfsSOTvo=,tag:DCR6bTBem7+WbnDSQO6icg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
# Vaultwarden Push Credentials
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-push
type: Opaque
stringData:
  PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:LBPxjkcH29pem1o5pekQS2d40KT9nG9YSD36aZfuWgWfxnNY,iv:DigQl6O80SSFDmsyqqr9IFQmRteOvRQswWjyvO5ggXA=,tag:WDSj78Z7Mkp6Mz82X/6VMQ==,type:str]
  PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:tA4aNEfTVNkLqf9Vc7FfAW9g2Yk=,iv:r3nn4x0yaO3a1anPvoYAOzJzoc6yaotkULPhmW1G6k0=,tag:mUkrnGzuhj5MkCPHyirCPw==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaWhaL293Y3BXQ2VHTHMr
        UEVKZ2tFYlJyejZoL1Q5ZGJDc3dZOFdWMmlrCi9UTWhZSmNQa1hyclp2bGVUUHRK
        M3g4MitCU1ZBZFNBN2U0b1RLRDBJRHMKLS0tIGZ0amJYOGZZQ3JjazVyRXc5TzJQ
        VHJpNWFsY2FPb3d0TGErcHBWd2FVM28Kbd6XbWiEKTFmYzYG3sPd/p28Udf3v6GD
        +hIf3e4Vqb/kChrSqYbpo/YCQzvIl5Jy3IuTWb/g9OUeprpD0S3R2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-17T14:03:22Z"
  mac: ENC[AES256_GCM,data:kdTctmTjxq5GVTLAVCTOj6p8orZlFxumgJfr5voWqZfJBZeDjRR8RKZ/DISaJfRG8YKTreZv5mJChTvZbnoRKqsxMnRBaIpR5z15Na/+L18EmpwlqXgO84bnbshfu9J33XTNI/E7QsKBroKk7Qq2hJTIZ73evXjTnMeiSAjgQCU=,iv:uMACNO/divpeSz8KIuOfBkV+yiedfYgDLmbNfsSOTvo=,tag:DCR6bTBem7+WbnDSQO6icg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
# Vaultwarden SSO Credentials
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-oidc
type: Opaque
stringData:
  SSO_CLIENT_SECRET: ENC[AES256_GCM,data:Wy7zfRePWgxqOur9MVSUnhLxb5MBtDAYFFhXaz2z12s=,iv:B7eRVGxLIVgmnXCMBgD/NL9A3zurn/hVz3yRqIbX0wE=,tag:PQB5JO9htmrM7F0/tdveWg==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaWhaL293Y3BXQ2VHTHMr
        UEVKZ2tFYlJyejZoL1Q5ZGJDc3dZOFdWMmlrCi9UTWhZSmNQa1hyclp2bGVUUHRK
        M3g4MitCU1ZBZFNBN2U0b1RLRDBJRHMKLS0tIGZ0amJYOGZZQ3JjazVyRXc5TzJQ
        VHJpNWFsY2FPb3d0TGErcHBWd2FVM28Kbd6XbWiEKTFmYzYG3sPd/p28Udf3v6GD
        +hIf3e4Vqb/kChrSqYbpo/YCQzvIl5Jy3IuTWb/g9OUeprpD0S3R2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-17T14:03:22Z"
  mac: ENC[AES256_GCM,data:kdTctmTjxq5GVTLAVCTOj6p8orZlFxumgJfr5voWqZfJBZeDjRR8RKZ/DISaJfRG8YKTreZv5mJChTvZbnoRKqsxMnRBaIpR5z15Na/+L18EmpwlqXgO84bnbshfu9J33XTNI/E7QsKBroKk7Qq2hJTIZ73evXjTnMeiSAjgQCU=,iv:uMACNO/divpeSz8KIuOfBkV+yiedfYgDLmbNfsSOTvo=,tag:DCR6bTBem7+WbnDSQO6icg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
