---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-opentelemetry-collector
  namespace: monitoring
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts/opentelemetry-collector
  ref:
    tag: "0.172.0"
    digest: sha256:3832aa2110e07da55e66648c2cc6ecfdf690ac5b25ca4f410607d5d65dea228e
