apiVersion: apps/v1
kind: Deployment
metadata:
  name: speaches
  labels:
    app: speaches
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speaches
  template:
    metadata:
      labels:
        app: speaches
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: speaches
          image: ghcr.io/speaches-ai/speaches:0.8.3-cpu
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: HF_ENDPOINT
              value: "https://hf-mirror.com"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
          volumeMounts:
            - name: hf-hub-cache
              mountPath: /home/ubuntu/.cache/huggingface/hub
      volumes:
        - name: hf-hub-cache
          persistentVolumeClaim:
            claimName: speaches-hf-hub-cache-pvc
