apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: speaches
  labels:
    app: speaches
spec:
  selector:
    matchLabels:
      app: speaches
  endpoints:
    - port: http
      path: /metrics
      interval: 20s
