apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speaches-hf-hub-cache-pvc
  labels:
    app: speaches
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
