---
apiVersion: application.logto.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: oauth2-proxy-credential
  namespace: prod
  annotations:
    crossplane.io/paused: 'true'
    crossplane.io/external-name: m8rwqva1rsy9p2b3tbsad/REPLACE_WITH_EXISTING_SECRET_NAME
spec:
  managementPolicies:
  - Observe
  forProvider:
    name: REPLACE_WITH_EXISTING_SECRET_NAME
    applicationIdRef:
      name: oauth2-proxy
      policy:
        resolve: Always
  providerConfigRef:
    name: isning-logto
    kind: ClusterProviderConfig
  writeConnectionSecretToRef:
    name: oauth2-proxy-managed-oidc
