apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: newapi-route
  labels:
    app: newapi
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: default-gateway
  hostnames:
    - "llm-dash.isning.moe"
  rules:
    - backendRefs:
        - name: newapi
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: newapi-api
  labels:
    app: newapi
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: default-gateway
  hostnames:
    - "llm.isning.moe"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /v1
      backendRefs:
        - name: newapi
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /v1beta
      backendRefs:
        - name: newapi
          port: 80

