apiVersion: v1
kind: Secret
metadata:
  name: newapi-secret
type: Opaque
stringData:
  SESSION_SECRET: ENC[AES256_GCM,data:VB8ityrqYV6TBC++K9a2YAWppEeE1YZ17XhYxIhlaNXjWpyXTUClBchK+kxJRuHaVl01Ti1oOtU/6pBVJUUsgQ==,iv:JfVYMWwoWQBTg7ti/xhL5TfLMEu77uxXKQcf1jw1DY0=,tag:CwsqOgYuuaLSznpiAXl6ew==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVm0yZFI5aXhzTzlpWGtz
        NUFnOUllVGJnR0kvU3RmZDMrdjM5d3Fwb0FrCnRsaXZsVlpJTjBienJDOWp0b1R1
        OURIaDI1WE9mTmVVbytBZFRINmdlOTAKLS0tIHBhYWtEMVlkc1NuYnhrMnZCc2t3
        dkh6Y3kvZlJSS2Y1TGNtRUVaM2d4ZFEKG5b8ExMsYvRiqsLpO9BdvgUG2Ywl1ElP
        9SoGepa24K+6psPj1iBQIsPkCJgy/8dKZu5F4fTYDci/lx0JkjJd9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-20T11:33:49Z"
  mac: ENC[AES256_GCM,data:FcsjovLoLmhGFd1NFSthC6fyfiFynIdyYw24vh93ryFXNIenQ30UmLLWc1IVE0CYyLrrl2Th55kGjD6CFeiH67dMn7ogxA3pRYj0AqjqTgHtlSi1pE00A4VPIl25JtIycfhovzJlS3PU2gSaQv6GT1OUU3gx3DcY2gxCtZ6nRAY=,iv:VkHqjYRlom27phRRBim9otChBbALeRKZ+2A4xihvTrk=,tag:7Zt1V28LHbC7cMaXvxbFQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
