---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: clirelay-ext-auth
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: default-gateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts:
              - clirelay.isning.moe
            paths:
              - /manage*
              - /v0/management*
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: clirelay-deny-non-admin
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: default-gateway
  action: DENY
  rules:
    - to:
        - operation:
            hosts:
              - clirelay.isning.moe
            paths:
              - /manage*
              - /v0/management*
      when:
        - key: request.auth.claims[roles]
          notValues:
            - clirelay:admin
