apiVersion: v1
kind: Secret
metadata:
  name: clirelay-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:GTi4pjdbmNI2+GDFmBGzPBiZHvECVKemLu4SyoRwVr9CTxElMQzKy5bQ+jK+GdE08/k=,iv:DSEeFzeJFuC2hBCnOlyhOy2MZF5GAc+OA4MMtBDgAoE=,tag:lm7EmqVsG/3m23Unrb8Zqg==,type:comment]
  remote-management-secret-key: ENC[AES256_GCM,data:h1NF0ia2a+0=,iv:nn4Fe4KzVDfNhY+jObNItP0DqsK8mDVD+REQ3OukEJk=,tag:PriXmaYxX8leaHq8Orny0w==,type:str]
  CLIRELAY_API_KEY_NVIDIA: ENC[AES256_GCM,data:Waf16rnLYIFM5elr/hZtTDsUb4t1mGvNeQ3GB82S+vOtAsVfCdpbG4j1VAM3tpHc2V39vPjsDCq9z4VKDdiX71olSc82Dw==,iv:GrTnFILSWaAK9aopYcl7FMoIAhymDRsAtX2eYBiP3e0=,tag:Nj25nJMi3fW4QZJeOZclqQ==,type:str]
  CLIRELAY_API_KEY_MODELSCOPE_GLOBAL: ENC[AES256_GCM,data:8jnwnfLy9xLF/kTh0JLSZ0opWvFEwzLrm1Gx2SizY9W4FXH73+6f,iv:7KmapbL6SWBxykdfdpX8hlsH2PR4Vednh3DQNRSYqpY=,tag:8kbwZ5cRywsvzvFn4dqIxQ==,type:str]
  CLIRELAY_API_KEY_GITHUB_MODELS: ENC[AES256_GCM,data:UtqRlx98gm/jaLDsjrd5dQOuIquFnrGcADr15K9IfAozWTvFCtwfjWKxUjfGuVJuN37qk+flNe7199a+rxaPIdU3rOQsmuE+To/zUnJorHS3pYKyoTHM2Q5AmHrk,iv:m6s3V4XM0NiDCbAVAp75zZWykAAQVowGzvVvawxexEw=,tag:YGGFu7UH7VwBVqBc2poaYw==,type:str]
  CLIRELAY_API_KEY_BIGMODEL_CN: ENC[AES256_GCM,data:0RXsw3yig+fzNQHBZNRURB0WM/VPAtt9dUJ6Qkjc1+0Vq95y/N4qz3NaGBBnkjrm3A==,iv:cOpGIgLgikU/fXX47RPfRfw1yeW5upj1qZig9g3LuPk=,tag:zxoj1ddFVJPiCeh6t6NT/A==,type:str]
  CLIRELAY_API_KEY_MODELSCOPE_CN: ENC[AES256_GCM,data:XTHYFJSMDxbPtJ3JCudQ9Kvtki8zTJDZX0yA/kHsF7aLxqFrGnHn,iv:GylERVt0ekfAFuRGj4Q6tyz0E5fZs/G5bDG33Mmm4nM=,tag:WWicP9l+CvyV+SNx1Zs4pQ==,type:str]
  CLIRELAY_API_KEY_GROQ: ENC[AES256_GCM,data:ZrIyfkkYlZyq0CwywVMI+j2aXkic1f7OzHaTzOTp4yk9ac3uRjDVAumE6W5VNAllQqLvVFYMaSA=,iv:lold74Z3NpJV510eaOE2oWxDuhTZZlM43lQPvZf8lmQ=,tag:cylOyIZbx6pUVJviZP2knw==,type:str]
  CLIRELAY_API_KEY_GOOGLE_AI_STUDIO: ENC[AES256_GCM,data:F9B6HdITD9mkZtHjmHyss6MUvO3RpDkyuS6jWwOpFTF3snYxUj2R,iv:p6c4MVR/0IX1Wivonqw3UWQ1QpSvmcfh0MynzwMPqsw=,tag:Z0s5+qcs0bhpwOEH6GSThw==,type:str]
  CLIRELAY_API_KEY_CLIENT_ASTRBOT: ENC[AES256_GCM,data:NUGC0lXX0sK0wCNVggZXwQjPlFU1MisqK8LAq1TAn9fYEYk=,iv:atWoZeXUJroee5CsakAAY0s6L1GanR0TkK9mLBjCKec=,tag:5tDGR/BvIhxRGT1aj/g0HA==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUzlzaFNpTXpJbzc3d1NN
        R1F5SjhMQTBBQ2NNZjl5ZHV2TEhCM05FUVRRCkUyNjRXYlZRMUYwYmNjOUdFNVZU
        cGk3UjY2YmJaWU41SGkzcFZJcitHWEEKLS0tIFZvWWNSdUQvbm1EV1FIclROUnc4
        bDRsNG5mVG5BcHA4YkxHRC9lZ1lrTVEKsdao9Qdyq6b0CGi6bnzloT1+lrKyi8qQ
        4yCJd33B0w+Q0+4hOdhmQuwDGVFLvi32kcCg3oGR0hwxvZ9rTACYwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T14:18:20Z"
  mac: ENC[AES256_GCM,data:ENak8vVrL2NKGSfrfyNeYSwOvZmiVH9e/VvgHjcHPN8qcnsr/1HWJLc1qgrIGRcLMmZfx1wtxMQ2yl24MdFQmf0ec9FmJ9fwXKimtjfsOBFVaVAhsoI2IyQ5WcRX8L6PR5OgLaZRzzj3DbM5S7dV1t7PVVRLsA/QJtVdodWumK4=,iv:SK6TLz3BLbdRJoVR2t6AfCPCAapkPQtNIXnBCzkFmE0=,tag:B3XFXc3se81/403LaLksmg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
