apiVersion: v1
kind: Secret
metadata:
  name: clirelay-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:y+wgrc3rg/l+ND80IZMlvhM4MqHeuK/ufP03+B9n5z8x6mpJBTYXxaZslOlohWZt9/Q=,iv:yKNdq11bvZAOQ+VAq3LoXBUV+wVa5pI3seACTWdEvSM=,tag:mo9MUc1dLhZiKmtEM1Ic1w==,type:comment]
  ENV_REMOTE_MANAGEMENT_SECRET_KEY: ENC[AES256_GCM,data:h+QQoKGVJ10=,iv:qQ8FJiSn9YKqeb8I5yuts3oiDEC/nUdNXl2JBSrwTvc=,tag:AgOzzAKaZZEu1XZP8i8RAA==,type:str]
  ENV_CLIRELAY_GEMINI_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:jupRh8zi3CtpEdc1ANW5Fo+1oMbqIMtrwCvkSNI9IASgqyWvGLLUMNslFOgfnc/NYBMYAMzT8gJSAzPbuqu4L8E9eu/aw0Po,iv:ogOQwlsbmycIHPAVe59A8EYN2xOLJnHcch1t8eFSPpU=,tag:zAr+lxa4RnUNo98lFwtMZg==,type:str]
  ENV_CLIRELAY_GEMINI_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:OtqXunjkCL1P/1ejr91RAU9U+I2VpLs3ozRB41lxj9eaNXM=,iv:m1gjixMedS9BOxWfjxFdQ5VVha6d/k2ZeoqunJzA7Hk=,tag:d/dIQbgWQjBfXaJyxSkvvA==,type:str]
  ENV_CLIRELAY_ANTIGRAVITY_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:weFu+t2/bvNwoYK1rHgpG0+P1yjs3HpUjqHOL0qC05PjnVPgJfYVUR7Li1mt/s2fcqPsXyNvJEcH45UojN0qHmqEMhAcqxqobA==,iv:/UOx88t5XB/zEkOgH7T1yxcJQBQS8EkGuM+cBRCvHJA=,tag:d+qrdtVQhUs/TX2tiD/vdg==,type:str]
  ENV_CLIRELAY_ANTIGRAVITY_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:d7fsLJvuKk28FcdtIi767hIajDCfm1cuLVl90zFyRCQzReA=,iv:t5Z3+12ukTA63g+LJk0/p49nsbeTbwtDtvWRh+J39IM=,tag:RLS3j5KoD4i3iUOX4X8o8w==,type:str]
  CLIRELAY_API_KEY_PACKYCODE: ENC[AES256_GCM,data:x90aO1AOQ8qVGI4Sd/SQ3DjvOA4ypkiTD+M75I0+s2f3DocCRcsfIQO07JvqhX/SxfCR,iv:e7d9dcQ1cLaUuSWAdCMWp7IlS5DVDIEgUGZKpHxAwfw=,tag:KzZSNVKg2TmpBYOlIgUtKQ==,type:str]
  CLIRELAY_API_KEY_NVIDIA: ENC[AES256_GCM,data:ULkZh54esXOFg8cKiNztXMoy3N4mA/WKyryhcn/PQFvw5NQnax2cvV1Curf0/p49Mz13JqMs4cUX62FQwCvRNpLtBQ6osg==,iv:l+5bqxw4iX2Z4zIJue//ob0sHBGJ79NX46QrSEPs9PM=,tag:tJy528mtf+oNv6UXJB1Ciw==,type:str]
  CLIRELAY_API_KEY_MODELSCOPE_GLOBAL: ENC[AES256_GCM,data:S9a84+OOArcDaza7kiufjjpZqbi0oXId85v/R1oMIBSD5qUPOr+w,iv:HBx6BJxYEKnb3t7f/py8x+zeOLTrezrSQZW/YyrcKtw=,tag:HgUg1PIpNKT6h4n2x9TFDg==,type:str]
  CLIRELAY_API_KEY_GITHUB_MODELS: ENC[AES256_GCM,data:bxoTk6T2Mc8LY1RCZFR0Grck8z+aH86ImDEf5qsH/3C+t+g5UYNC49XwywpsQXX0fSQaiDWiXLW4nWem6CR8uYtdnZZ2/ZYdB35u0GHSlBqmuC7j1b35zvw5zQ7j,iv:S7Oypw6wxIHoN5y6jGD9UEClcF+AWO0eW/NLBt8fbZA=,tag:+0BoQQbV8Ht44qleh4CwqA==,type:str]
  CLIRELAY_API_KEY_BIGMODEL_CN: ENC[AES256_GCM,data:OXub4L9QhiTxW/a7DJlv1wdCHh0KTsOSf22nvgAUvJ3LMORNEwqxxIcTXpTRfJlr6w==,iv:zT1texZrUIjn3LLNbygDE9RLvA2Ptd1xrYRs05d97ZE=,tag:7GRyoIPdQ58feRDcv9KDkQ==,type:str]
  CLIRELAY_API_KEY_MODELSCOPE_CN: ENC[AES256_GCM,data:3J73baU79VlQiZ3PF1NZhJrI8uoqIdWdF9fnffDKNhohuLtQvG13,iv:7+Ry0yfk1bR2Ldo1+RyWx39sH3WtHouD7od8K8zjI1g=,tag:e/RC02bvCs2ySSFvp3bEQw==,type:str]
  CLIRELAY_API_KEY_GROQ: ENC[AES256_GCM,data:UqiU3PATn4H97vUkOPkuYwMgw7T7I829pOTUgCGv1PrUx1ftChsDw6v8TJDAIToaQip8s+kj6oI=,iv:ey5lNkU6+YTQ8rb9ZQlEOtracYmuVsfYuUduvUr9eg4=,tag:WWJC8hC+tGkeMXVBcD6w6g==,type:str]
  CLIRELAY_API_KEY_GOOGLE_AI_STUDIO: ENC[AES256_GCM,data:a9sWJ3BLKzo5Avuer0K+8sezIiRUr6SvodMZWBLSMav5yPj8PdgZ,iv:D5i9mE4AV53cBK0g9lSQ6lGQSEOJBvjI/sryIhhn7vg=,tag:dADXiOpBFqwk6aVo0U0NOA==,type:str]
  CLIRELAY_API_KEY_CLIENT_ISNING: ENC[AES256_GCM,data:RSCoFqrwwcw8/zuWP3IJ6cSpm7SggaB29xFK1mtJTchYMuk=,iv:FR3E7a3qZWaXOzW8TAIUcMjxVsobxRBkhHIB7ImSJoA=,tag:B692hCvoHcQ5rHONV6mNuA==,type:str]
  CLIRELAY_API_KEY_CLIENT_ASTRBOT: ENC[AES256_GCM,data:ax7Oqe+7G2GU2/I0x3++Tg3w6Gfh99OCBPS4VPI3egKv+MU=,iv:FY3BclvTPt7K9jaghFRKPc+JEgny2ST9h01led+ggxo=,tag:MCINjIoOropCB6j4FU7A7w==,type:str]
  CLIRELAY_API_KEY_CLIENT_SIYUAN: ENC[AES256_GCM,data:sYvwR19gV4Fy2ayKvkPTcBjDtE42GKiuILQJvzL7UrzEPgE=,iv:1mwewB3IAKNRVTCJh/e1mnpiHWWnbRkgN6iTaSHGkhA=,tag:h11sBCZZKonoE9UxeENXbQ==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UmVTT2Rla1FkQVZNQlA0
        eXdIMjYxSVZsME9FdGtEc05ndENEU1BsRzJRCmZsc243b0c2SUxpRlNJL0dHaWxm
        NnFzcXVsU29Tai9LY3EvVE1NaWh6VGMKLS0tIGVaYWxrMGpJQ1NGaldSZEFoWmJk
        eUR5TStReUgvR2U5b0V3VGRzMVFJTGMKH78LcuB9+gEhf+9W171b3bEHVUVwP5ih
        yQ5KiOgCH17dSVS/edhbdee8q0+WM0208UO0jSn/7xLTF7Eby5u5lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-15T04:52:36Z"
  mac: ENC[AES256_GCM,data:WeUL8IAGzrkndz4ZSJCz3A1/H/ap/gNNaW//58ueHbXFEup9gBCMYiYouzAFBBYZnMWvoYAz67mVvPlD+PPzXTA3dGA1JA/KkUm3OYmmytN85851ulG+N//Z/jmlNyIpyrPhUwYX+EU/iGWtd8EHWw0p49+gArim1HhNz6FpBl4=,iv:hEeHAYtIi1Xux5Mzccs8uDNNZYeyObEK7FDkP9arKl4=,tag:9ISwwJZkhMQUu3z6nCe31A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
