---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  releaseName: tofu-controller
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: tofu-controller
    namespace: flux-system
  install:
    crds: Create
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    runner:
      image:
        repository: ghcr.io/isning/k8s-gitops/tf-runner
        tag: v0.16.3-custom-202605130729@sha256:3d52c13326298c621eca35101ff6d470c08d36133f324cf89876e7c2f219050b
      serviceAccount:
        allowedNamespaces:
          - flux-system
          - harbor
