---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  releaseName: headlamp
  interval: 30m
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: helm-repo-headlamp
      version: 0.44.0
      interval: 12h
  values:
    httpRoute:
      enabled: true
      annotations: {}
      labels: {}
      parentRefs:
      - name: default-gateway
      hostnames:
      - headlamp.isning.moe
    config:
      watchPlugins: true
      oidc:
        clientID: ${clientId}
        issuerURL: https://logto.isning.moe/oidc
        scopes: openid email profile offline_access roles
        usePKCE: true
        useCookie: false
        meUserInfoURL: https://logto.isning.moe/oidc/me
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 200m
        memory: 512Mi
    volumes:
    - name: plugin-flux
      image:
        reference: ghcr.io/headlamp-k8s/headlamp-plugin-flux:v0.6.0
        pullPolicy: IfNotPresent
    - name: plugin-cert-manager
      image:
        reference: ghcr.io/headlamp-k8s/headlamp-plugin-cert-manager:v0.1.0
        pullPolicy: IfNotPresent
    - name: plugin-kubevirt
      image:
        reference: ghcr.io/naval-group/headlamp-kubevirt:0.2.2
        pullPolicy: IfNotPresent
    volumeMounts:
    - name: plugin-flux
      mountPath: /headlamp/plugins/flux
      subPath: plugins/flux/
    - name: plugin-cert-manager
      mountPath: /headlamp/plugins/cert-manager
      subPath: plugins/cert-manager/
    - name: plugin-kubevirt
      mountPath: /headlamp/plugins/kubevirt
      subPath: plugins/kubevirt/
