apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunasync-worker-fs-apt
  namespace: opentuna
  labels:
    app: tunasync-worker-fs-apt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunasync-worker-fs-apt
  template:
    metadata:
      labels:
        app: tunasync-worker-fs-apt
    spec:
      nodeSelector:
        opentuna.isning.moe/node-role: mirror
      tolerations:
        - key: opentuna.isning.moe/mirror
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
        - name: tunasync-worker
          image: tuna/tunasync:latest
          command: ["/usr/bin/tunasync", "worker", "-c", "/etc/tunasync/worker.conf"]
          volumeMounts:
            - name: config
              mountPath: /etc/tunasync
            - name: efs-storage
              mountPath: /mnt/efs
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "4000m"
      volumes:
        - name: config
          configMap:
            name: tunasync-worker-apt-config
        - name: efs-storage
          persistentVolumeClaim:
            claimName: opentuna-efs-pvc
