---
kind: will-be-ignored
metadata:
  name: will-be-ignored
spec:
  template:
    spec:
      volumes:
        - name: cri-socket
          hostPath:
            path: /run/k3s/containerd/containerd.sock
