---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-atlantis
  namespace: runatlantis
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/runatlantis/charts/atlantis
  ref:
    tag: "6.16.0"
    digest: sha256:1692f79c9b0a3a737d24b0dacd841bfd9aa0021babf46d9dccf307b5685acd79
