---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-atlantis
  namespace: runatlantis
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/runatlantis/charts/atlantis
  ref:
    tag: "6.9.3"
    digest: sha256:d236ccd21842ba3b8dd62519fcb06fe3f30ee51dd4bad83ac025d82d63c941c3
