---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-grafana-operator
  namespace: grafana-operator
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
  ref:
    tag: "5.22.2@sha256:8cb589d52db1d1de3fec53078bc7f0547c4132d2bb309c6fc7645e8010fd4bfa"
