apiVersion: v1
kind: Secret
metadata:
  name: paseo-secret
type: Opaque
stringData:
  PASEO_PASSWORD: ENC[AES256_GCM,data:1SS3L+jrhlOuX0bhAlRgH52xnxVeNBA30Iy1ODRdv1ylSJsA4PsSDQilBg==,iv:e1HdEeRVp9sTyc4qi6LnILw0fT+XHCNUTbxHPHFA83A=,tag:tEsdQPyktlE87uiWQvO6nQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a2RNNFZrcnRzaEhJRW12
        Z0pmNEZTWGQxNCsxQmpacjJwSHAwMmdhRWhZClUwdU9WOGVqM3RGUS93WTV3QXNF
        Q1ZTWkRTN3NSUS9LQWR0Rmo1dlpsc00KLS0tIG8xYVpWQVJzZU9WMWRzRHY2YkNx
        K3Q3eWo2eUwwZDRZQVVFMyttS0dvckUKFF2SG/baR9TO1qapy+ARcq4fS+pZheZq
        wv20ON70haXXy+BE6k2Tq+uw1pMGmpgb52hAKz8KOW7cDO6I7cu7Vg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T18:45:27Z"
  mac: ENC[AES256_GCM,data:qAnylhQdz/Aoa+hheY/aNBL0EncUvcND6Qna514/mOqI+zTlqQtkmmG44YLjwIbE68+JgAJPqB/vsnpLo+e5CqGQZs0LS/c/3zbo32WIfWkPdtixw8c5y1xyCNGkhmLi0aA25koyhcruXeYMTpPJf9rKevz/9T/eMMJ0USICy6s=,iv:RyCtZwcKih8yu8ZviNA4Ry+dpaB7WqqEbNUrb11vJTQ=,tag:UJrM8fogKYI0WDd5IULFcA==,type:str]
  version: 3.13.3
