---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
  - name: infra-namespaces
  - name: infra-controllers
  - name: infra-configs
  - name: identity-applications
  - name: gateway-identity
    namespace: prod
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/kubevirt-lab-1
  prune: true
  wait: true
  timeout: 1m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
    - kind: Secret
      name: kubernetes-cluster-managed-application
