---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: management-providers
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  timeout: 10m
  dependsOn:
  - name: infra-pre-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/pre-controllers/base/crossplane/providers
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    name: provider-upjet-logto
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    name: provider-upjet-harbor
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    name: function-go-templating
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: management-configs
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  timeout: 10m
  dependsOn:
  - name: management-providers
  - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/pre-controllers/base/crossplane/configs
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: identity-applications
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  timeout: 10m
  dependsOn:
  - name: management-configs
  - name: logto
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overlays/kubevirt-lab-1/identity
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: logto
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  timeout: 10m
  dependsOn:
  - name: infra-configs
  - name: management-providers
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/logto
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  targetNamespace: prod
  commonMetadata:
    labels:
      app.kubernetes.io/env: prod
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: logto
    namespace: prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-identity-consumers
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  timeout: 10m
  dependsOn:
  - name: identity-applications
  - name: infra-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/configs/overlays/kubevirt-lab-1/identity-consumers
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
    - kind: Secret
      name: kubernetes-cluster-managed-application
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-identity
  namespace: prod
spec:
  interval: 5m
  retryInterval: 30s
  timeout: 10m
  dependsOn:
  - name: identity-applications
    namespace: flux-system
  - name: infra-configs
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infra/configs/base/gateway/identity
  prune: false
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: oauth2-proxy-oidc-variables
