---
apiVersion: application.logto.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: harbor-credential
  namespace: harbor
  annotations:
    crossplane.io/paused: 'true'
    crossplane.io/external-name: 534gp0torf1s2dsokwcwo/REPLACE_WITH_EXISTING_SECRET_NAME
spec:
  managementPolicies:
  - Observe
  forProvider:
    name: REPLACE_WITH_EXISTING_SECRET_NAME
    applicationIdRef:
      name: harbor
      policy:
        resolve: Always
  providerConfigRef:
    name: isning-logto
    kind: ClusterProviderConfig
  writeConnectionSecretToRef:
    name: harbor-managed-oidc
