---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-loki
  namespace: monitoring
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/grafana/helm-charts/loki
  ref:
    tag: "7.0.0"
    digest: sha256:9b0f44213a16fea700852402ea05f45ce685fddb5a2fbe0d7e932e1a94610707
