apiVersion: v1
kind: Secret
metadata:
  name: sub-converter-suburls-secret
  namespace: egress-system
# Separate multiple sub-URLs with comma, and each sub-URL is in the format of "name:url"
# Optional: set NODE_SELECTIONS like
#   HongKong = [ 'HongKong URLTest', '[YZT] 香港1', '[YZT] 香港2' ]
#   UnitedStates = [ 'UnitedStates URLTest', 'My US Node' ]
stringData:
  SUB_URLS: ENC[AES256_GCM,data:Hk3AeWuI+u65iW6iDHwsFT5hYqjwFU2IthNdgxs3Ef0MRIU/qAiaEucMCnpF+R3d3xyMaJHcB/2/h3KccvCQPTpk8zZApkYjzVp/3nYRnT0mg7Ep2nVj2/bmrBwEJ29xf5Pllzid36XRyIKYGxMBFs8IvT4yf34d8zRsYgAc0ktuZTqHZJWUMuDUrlQKO7ndBzMlOE18gXNi5qbSZfooUtkVDi75TT5w6AO8ZNUSd2HPgAWwt1NDCA1anr3s00zrAqI+i5OEc/ywkxBRSDI=,iv:54HA8SuHq+eRuyuCficBIgBQHWPwqf0W93yyAHN5lPc=,tag:woEvLvGt28wdqntcRP6ZIQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Y25RazQwWmljaVpFOEVV
        YVNmVUN1MThyTmdQN29RK1FkdllONnkzbEVNCk1iZHhDWG45NnZHOHE4bXJZK3dk
        NUN3M0YzRW92MEVTZ0F2WHFTTklpZVkKLS0tIERRWm1pSUlmVjVMNk5OM3JGeUps
        SE9xVk9vUmw5V1ZTaWNtdXJnWDQxQ2sKfGjHG6kYGUSJ/9vFNLmXQfWg3JKCtLKN
        M8C4dwQZVF69gBLL2UnQMuxZDWF/WPkSZ+qRxXLN74l9k68KTimeWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T19:24:57Z"
  mac: ENC[AES256_GCM,data:8EUeGeAEbnBavzEF+E9EKD1CaxDid8jG26ETZYwCM23QCNECovMyMlqqwZPumWHeOtwNc2GJahDijGI7vBtSN2M6HKh51O7TNNq5Fo4CAkcxgYmE+i1PXELP702f5lJ+qlaW1ig5SBFZFeeXMYv7wSmJnE2BHBcRiisCISPXuZM=,iv:Zcg18JBJzSerbQaU2xrNfPDc8Mhx7UQO4KePcVdalqA=,tag:RxWjnvTSRvCeeGAZxPME1g==,type:str]
  version: 3.13.3
