apiVersion: v1
kind: Secret
metadata:
  name: sub-converter-suburls-secret
  namespace: egress-system
# Separate multiple sub-URLs with comma, and each sub-URL is in the format of "name:url"
# Optional: set NODE_SELECTIONS like
#   HongKong = [ 'HongKong URLTest', '[YZT] 香港1', '[YZT] 香港2' ]
#   UnitedStates = [ 'UnitedStates URLTest', 'My US Node' ]
stringData:
  SUB_URLS: ENC[AES256_GCM,data:fsbGJmp1CYPOGRPni52DMq6H8zUkfqPd3Vu27rtyCFbXI0dp3ADldOTzTI+gliUUwawgUpGRkvMgoDRW8SNqV4/rY9jGVYdjIIEY+t6K8iawgHXR7zLlgSIGiNUDJGGivFsf1Z5Ne9cIU8QYwZdoR9sklyjcrpINLUHFeYgKludP3OOUaJtZjGbxZXDWOmaOe5QjHO3QbliQwCeP6PdkqkE=,iv:wiXHzRLz2fotQWsY9ir23xBZjUQVYvjcl8W0ppGc5+k=,tag:GojbaGazvmdVv6ybh+QqOw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSEFlc1JhNWw2NCtzbmt1
        aHNyN21hVm9Xc1I0aVpIQjNMSGYzT1FXYnkwCk5OVGx2RW9RZ1VlNVRjK1BvMW5V
        N2lSWVJjcXhOSmZ4OGNGT1pEKy91TjAKLS0tIHBrb2tvdkdlUzJWVWdYaXNNR09l
        V3Q4QTRhbm5BN1o5R2g2d01ueWRGWWcKwTHDQwlm/Y9XqKbYExhwKuWIDi9yke8F
        6FfnmKwSK07DVVJV+NX0MWFsPqZD1vxIVCgr2BRi9WIjvltSQy/sRQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-19T17:07:05Z"
  mac: ENC[AES256_GCM,data:+AvBrENyKASG7xBGRLSHkJTZa/QZ4DR7M+Y3+B4YfdZWJZDDA8Gk3vtdEN14Go5ksAIYiNnK38liHRYs8MQyV2/RQzCregJq+zL/jNOwyI/G7D9RNkpE5456diCmJ22FTpw1N9emZSJTWh+9FADaKqEQQ7Njizk5UB0FLFlS/F8=,iv:JUwCttxa/T/aXeH5QZuUfdms7uxVW2O2hj6IIEqDuLQ=,tag:v/MCriHVfMbtBsod3dt7uw==,type:str]
  version: 3.13.1
