---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxy-engine-work-cache
  namespace: egress-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
