kind: will-be-ignored
metadata:
  name: will-be-ignored
spec:
  values:
    vmagent:
      spec:
        scrapeInterval: 20s
        externalLabels:
          # For multi-cluster setups it is useful to use "cluster" label to identify the metrics source.
          cluster: k3s-test-1
          env: test
      ingress:
        hosts:
          - test1-vmagent.isning.moe
