variable "edgeone_zone_id" {
  description = "EdgeOne site ID containing isning.moe"
  type        = string
}

variable "edgeone_origin_record_id" {
  description = "Existing EdgeOne origin record identity; null only for initial group creation"
  type        = string
  default     = null
}

variable "acceleration_domain" {
  description = "Wildcard Coder workspace acceleration domain"
  type        = string
  default     = "*.coder.isning.moe"
}


variable "gateway_service_name" {
  description = "Service generated by the Istio Gateway controller"
  type        = string
  default     = "coder-gateway-istio"
}

variable "gateway_namespace" {
  description = "Namespace of the dedicated Coder Gateway"
  type        = string
  default     = "prod"
}
