variable "edgeone_zone_id" {
  description = "EdgeOne site ID containing isning.moe"
  type        = string
}

variable "acceleration_domain" {
  description = "Wildcard Coder workspace acceleration domain"
  type        = string
  default     = "*.coder.isning.moe"
}

variable "enable_origin_acl" {
  description = "Enable EdgeOne Origin Protection after the site plan supports it"
  type        = bool
  default     = false
}

variable "gateway_service_name" {
  description = "Service generated by the Istio Gateway controller"
  type        = string
  default     = "coder-gateway-istio"
}

variable "gateway_namespace" {
  description = "Namespace of the dedicated Coder Gateway"
  type        = string
  default     = "prod"
}
