# https://fluxcd.io/flux/components/helm/helmreleases/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  releaseName: cilium
  interval: 30m
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 12h
      version: "1.19.*"
  # https://github.com/cilium/cilium/tree/v1.19.0/install/kubernetes/cilium
  values:
    # ======================== Tuning Cilium ========================
    # https://docs.cilium.io/en/stable/operations/performance/tuning/
    # https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/
    kubeProxyReplacement: true

    bandwidthManager:
      enabled: true
      bbr: true
    loadBalancer:
      mode: dsr
      acceleration: best-effort
    bpfClockProbe: true

    # ======================== Work with Istio ========================
    # https://docs.cilium.io/en/latest/network/servicemesh/istio/
    cni:
      exclusive: false
    socketLB:
      hostNamespaceOnly: true
    # disable L7 Proxy
    l7Proxy: false

    # ============================  Dual Stack  ============================
    ipv6:
      enabled: true
    # -- Enables masquerading of IPv6 traffic leaving the node from endpoints.
    enableIPv6Masquerade: true



