apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-agent-sandbox
  namespace: agent-sandbox-system
spec:
  interval: 12h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/unique-ag/helm-charts/agent-sandbox-controller
  ref:
    tag: "1.0.1"
    digest: sha256:cb1bbacda71ca8d86078d8b019f1e3efcb8883e5245ffd57472a6f7c66158717
