apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agent-sandbox
  namespace: agent-sandbox-system
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: helm-chart-agent-sandbox
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    fullnameOverride: agent-sandbox-controller
    image:
      repository: registry.k8s.io/agent-sandbox/agent-sandbox-controller
      tag: v1.0.1
      digest: sha256:e1787f95cda406e2d81322e8637b6dfa2d77514fbbd0536a872b8e5d409b7154
    replicaCount: 1
    extensions:
      enabled: true
    router:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: "1"
        memory: 512Mi
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ALL]
