apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agent-sandbox
  namespace: agent-sandbox-system
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: helm-chart-agent-sandbox
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  postRenderers:
    - kustomize:
        patches:
          - target:
              labelSelector: app.kubernetes.io/name=agent-sandbox
            patch: |
              - op: replace
                path: /metadata/labels/app.kubernetes.io~1version
                value: v1.0.5
              - op: replace
                path: /metadata/labels/helm.sh~1chart
                value: agent-sandbox-1.0.5-repack.1
  values:
    namespace:
      create: false
      name: agent-sandbox-system
    image:
      repository: registry.k8s.io/agent-sandbox/agent-sandbox-controller
      tag: v1.0.5@sha256:28a9cbdbfd6ac0a4e5c7e9261ace1aa30ee2da681cb640dccdfed98e8dd9d98b
    replicaCount: 1
    controller:
      extensions: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: "1"
        memory: 512Mi
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ALL]
