---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-k6-operator
  namespace: k6
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/grafana/helm-charts/k6-operator
  ref:
    tag: "4.3.2@sha256:6623d3188ac5c12ab101ac99aa05c8853405cc0a93215c92fa3499f8d7197ac1"
