apiVersion: v1
kind: Secret
metadata:
  name: bay-api-key
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:SMww0Ve8xMY7GV69W42ci3gmdp2hdgnqTKlVxMhYwIDoQYWgYrcDGHHWBdiRmOdSPimEITlO/Q/bhnQUT1ze5Q==,iv:U4p/wZ7Zr5VxIOVvgsJ+VdrSWr6f9S8cMNUbhYT+Jyg=,tag:omYOYaGUasGKYI8qOpc1Tw==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dDJEVmE4TnZjendmTEtX
        L3YvbFAxa2ppZ2I0cW8wY0ZBWUZEZnh2Qkc0Cmg1M2FKbU40QkZJaGJMNGlqeThl
        K2tTanVSUVJUVlZadFJ5SEpkQjFtMUkKLS0tIENnZHowYXFKQUk4MWh4OU5BRmQ2
        Si9ESmxCQlNPM3Zwem54RDc1UTZtN0kK44g6WaFnds0xjcytjORhbAzqpRjFwyag
        gWsZM9kf1SupWRVDBSq6HWYHeud9X3vjHbILXwrVEHRqFtrehti7TA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T11:27:12Z"
  mac: ENC[AES256_GCM,data:weE9C6HUyyOTyAzORER0P3A/TtDL/DZCGWqmviEAzbHzwwGYQbogi640RD+ZPJY8KRKHL+RcWY7D+QSbzvW46F1zcDe1p5Bzh2kKjNOqoJ+1f8R/3IrKlep2KKw5JjMDQQ0NSFb6H27WqUSzumOn+63Y5JSlo6efpJGzCen832s=,iv:rcFKIQxo5mixth4WLTo2R+I6i2RIwW63u+nXI2L3yHw=,tag:t0sBPSF/hx8GjjqNekvqVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
