---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
  ref:
    tag: "0.74.1"
    digest: "sha256:dbf189a348da62eee412015d834b8eefc09c5a351255bdfb0d1c99a579db3f66"
