# Copy to .management-credentials.plaintext.yaml, fill locally, then SOPS-encrypt.
apiVersion: v1
kind: Secret
metadata:
  name: logto-management
  namespace: prod
type: Opaque
stringData:
  credentials: ENC[AES256_GCM,data:qlmpo7s0GOS8Z57ee0Nt+Ps/+018bYMhkQn/37VsJ1TY5qZn0VYNPyMhbxxdajGL2SlQdPE91ygbS6CTu1ENgf645sodlbN/e5MONAG6WA7E0pflE+L4vEpG7M8G+c9TLuQ/dVUJTzmNe6KlYiVaqOgxl1+HZK/ADOkJq/HZEaTgQ3JTXiqe+KAgeKeVHeuYSTJn+dLFC7tWetQYVybXnHSrEmXUAR/G1iV/PG/IQkDLVv5vfC3rkjdvllCN,iv:J0CkUUPfA7bKW4FcRw/ntNrria/Y01VTBcnSil6Rv/8=,tag:F8SqbxKNvXDPeHtcAaQ4Mw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S3ZBdWpteE5aSkI0OXYr
        N25SeWFoTFZDUjFKOXNQSSt1UC9CbDF4MVFJCmgrSEMzb1RITTFoUEwrc1dBbW9l
        bnFWN01rL3BBbWg4ZmRPVHNiVm5KQmsKLS0tIG5JRWdzNUllYjIrM1YwYU8zbnNx
        LzhibDJvWFZZOEQ2bmc4ZHJsMkVvc1kKFyjGADFlvgaC9OWdF0fjDdJzuipifPC5
        PEAW1IgmHFcT+rY5hGBgm69pwa0siC9e2eMEUD1kvVwpnOmdNBRXXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T09:42:50Z"
  mac: ENC[AES256_GCM,data:sPW3F3ZD1abpmr45qNkGOWbcVKjTwtxRTtIOXHdY43wSzndcSYB4DvKRHIj8Mbs0kjNqoDwEW2a2l9CrbQbCYCESyUdOWvURiwdjNno5Cit8pMG/mIbROi8T84VQmteFicJkz87TfgYnqZczKx4R8iqCFHoyhPL5YAbxjdVDk78=,iv:QwtXh/yfiFv97VW6rtmlD61c2zFdbjmiS0/Lk5uZJQk=,tag:6kRHFvpI3DMMZV7oGQmePQ==,type:str]
  version: 3.13.3
