apiVersion: v1
kind: Secret
metadata:
  name: logto-pg-s3-credentials
type: Opaque
stringData:
  access-key: ENC[AES256_GCM,data:AululeSaTJBanalccJXghH5HQObLdsp0hNUFR1HTmH0=,iv:kA1iwI2bWg3+BgKGb0/uf0+tEBXKmx6b9+OSQ6cfhL0=,tag:IGQo8f3I5TCBSlmQmH+EmA==,type:str]
  secret-key: ENC[AES256_GCM,data:L55x5j+F/31pfnpLZF2PPIUiOSJY40A0YgmCkuNwcR7BM99NlXYlOilAqfTibxnF1c6OHHp1yXbhpzuRa1gCrQ==,iv:Awxc1MRlSD9hqyv/++Tzi6wgxSqoZcEIUuj/fCytD+w=,tag:2EySASw9lNgHbZzV7DNCQw==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWWhla1FIOGtvdkorVUs4
        WmpteUhtbS81Z2JlSDlBbUN4bkJNQzJGdjFrCjN3bFhIWGF5S090eGMvSDdPeXJo
        Y2dOTUZyMDd6a1hsbU1MeG9JS0ZnSlEKLS0tIGljWlN5d0orNWdvOG9MS0FEckNp
        aGZsb3FkSUVPYWpOTjh1ajFMdTdtZEEKPg3hMoofi0JhcBN8skDl7m6axETzK3EK
        T8VxMWJEnIgkUuo3StvOpX1zVirL5Qxpa4NGa3//dPvBsEw8C+Mtdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-18T06:25:38Z"
  mac: ENC[AES256_GCM,data:NmyfG6D90q/PAqU3JgepxTEZxLkgCuOnBTKcARGbr8fURTxrwStFWdez0W0Nn+vs8yVJ2lAvQWj1+2ZHVmSxtQePtWlG11fsT/lVW7vIQEC8pj0EaG3ND5NRfTRdsmPwLoVO3e6w/aSztLAXigvMu9by6w4zYykwrun62wpM57g=,iv:7e2LXoyV5MafxdZ2zddmzVa7wBw1Rx4jExzNxQtSbxs=,tag:1fZdGo6qR6/Rgd1lFTUUJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
