apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: logto-pg-cluster
spec:
  instances: 1

  # Logto requires superuser access:
  # https://github.com/logto-io/logto/issues/6842
  # https://github.com/logto-io/logto/issues/8275
  managed:
    roles:
      - name: app
        superuser: true
        login: true

  bootstrap:
      initdb:
        owner: app

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    # Logto requires PostgreSQL 14 https://docs.logto.io/logto-oss/get-started-with-oss#:~:text=PostgreSQL,%40%5E14.0
    major: 14

  storage:
    size: 10Gi
    storageClass: local-path-nocow
  
  enableSuperuserAccess: true
