# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: kube-system
spec:
  releaseName: local-path-provisioner
  interval: 30m
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
        namespace: flux-system
      interval: 12h
      version: "0.0.34"
  # https://github.com/rancher/local-path-provisioner/tree/master/deploy/chart/local-path-provisioner
  values:
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 1m
        memory: 32Mi
    # Default value form k3s
    nodePathMap: [{node: DEFAULT_PATH_FOR_NON_LISTED_NODES, paths: [/var/lib/rancher/k3s/storage]}]
    configmap:
      # specify the config map name
      name: local-path-config
      # specify the custom script for setup and teardown
      setup: |-
        #!/bin/sh
        set -eu
        mkdir -m 0777 -p "$VOL_DIR"
      teardown: |-
        #!/bin/sh
        set -eu
        rm -rf "$VOL_DIR"
