---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  type: oci
  interval: 12h
  url: oci://ghcr.io/rancher/local-path-provisioner/charts
