# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: kube-system
spec:
  releaseName: local-path-provisioner
  interval: 30m
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
        namespace: flux-system
      interval: 12h
      version: "0.0.34"
  # https://github.com/rancher/local-path-provisioner/tree/master/deploy/chart/local-path-provisioner
  values:
    # Default value form k3s
    nodePathMap: [{node: DEFAULT_PATH_FOR_NON_LISTED_NODES, paths: [/var/lib/rancher/k3s/storage]}]
    ## For creating the StorageClass automatically:
    storageClass:
      create: true

      ## Set a provisioner name. If unset, a name will be generated.
      provisionerName: rancher.io/local-path

      ## Set StorageClass as the default StorageClass
      ## Ignored if storageClass.create is false
      defaultClass: true

      ## The default volume type this storage class creates, can be "local" or "hostPath"
      defaultVolumeType: hostPath

      ## Set a StorageClass name
      ## Ignored if storageClass.create is false
      name: local-path

      ## ReclaimPolicy field of the class, which can be either Delete or Retain
      reclaimPolicy: Delete

      ## volumeBindingMode field controls when volume binding and dynamic provisioning should occur, can be  "Immediate" or "WaitForFirstConsumer"
      volumeBindingMode: WaitForFirstConsumer

      ## allowedTopologies field controls on which nodes the volumes can be dynamically provisioned, an empty value means no topology constraints
      allowedTopologies: []

      ## annotations to add to the StorageClass
      annotations: {}

      ## Set a path pattern, if unset the default will be used
      pathPattern: "00-{{ .PVC.Namespace }}-{{ .PVC.Name }}"

    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 1m
        memory: 32Mi
    configmap:
      # specify the config map name
      name: local-path-config
      # specify the custom script for setup and teardown
      setup: |-
        #!/bin/sh
        set -eu
        mkdir -m 0777 -p "$VOL_DIR"
        if echo "$VOL_DIR" | grep -q "^01-nocow-"; then
          echo "Disabling COW for volume path: $VOL_DIR"
          chattr +C "$VOL_DIR" || true
        fi
      teardown: |-
        #!/bin/sh
        set -eu
        rm -rf "$VOL_DIR"
