# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: kube-system
spec:
  releaseName: local-path-provisioner
  interval: 30m
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
        namespace: flux-system
      interval: 12h
      version: "0.0.34"
  # https://github.com/rancher/local-path-provisioner/tree/master/deploy/chart/local-path-provisioner
  values:
    ## For creating the StorageClass automatically:
    storageClass:
      ## Set a provisioner name. If unset, a name will be generated.
      provisionerName: rancher.io/local-path
    
    storageClassConfigs:
      local-path:
        storageClass:
          create: true
          defaultClass: false
          defaultVolumeType: hostPath
          reclaimPolicy: Delete
          pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
        nodePathMap: [{node: DEFAULT_PATH_FOR_NON_LISTED_NODES, paths: [/var/lib/rancher/k3s/storage/default]}]
      local-path-critical:
        storageClass:
          create: true
          defaultClass: false
          defaultVolumeType: hostPath
          reclaimPolicy: Retain
          pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
        nodePathMap: [{node: DEFAULT_PATH_FOR_NON_LISTED_NODES, paths: [/var/lib/rancher/k3s/storage/critical]}]
      local-path-test:
        storageClass:
          create: true
          defaultClass: false
          defaultVolumeType: hostPath
          reclaimPolicy: Delete
          pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
        nodePathMap: [{node: DEFAULT_PATH_FOR_NON_LISTED_NODES, paths: [/var/lib/rancher/k3s/storage/test]}]
      local-path-nocow:
        storageClass:
          create: true
          defaultClass: true
          defaultVolumeType: hostPath
          reclaimPolicy: Delete
          pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
        nodePathMap: [{node: DEFAULT_PATH_FOR_NON_LISTED_NODES, paths: [/var/lib/rancher/k3s/storage/00-nocow/default]}]
      local-path-nocow-critical:
        storageClass:
          create: true
          defaultClass: false
          defaultVolumeType: hostPath
          reclaimPolicy: Retain
          pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
        nodePathMap: [{node: DEFAULT_PATH_FOR_NON_LISTED_NODES, paths: [/var/lib/rancher/k3s/storage/00-nocow/critical]}]
      local-path-nocow-test:
        storageClass:
          create: true
          defaultClass: false
          defaultVolumeType: hostPath
          reclaimPolicy: Delete
          pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
        nodePathMap: [{node: DEFAULT_PATH_FOR_NON_LISTED_NODES, paths: [/var/lib/rancher/k3s/storage/00-nocow/test]}]

    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 1m
        memory: 32Mi
    configmap:
      # specify the config map name
      name: local-path-config
      # specify the custom script for setup and teardown
      setup: |-
        #!/bin/sh
        set -eu
        mkdir -m 0777 -p "$VOL_DIR"
        if echo "$VOL_DIR" | grep -q "00-nocow/"; then
          echo "Disabling COW for volume path: $VOL_DIR"
          chattr +C "$VOL_DIR" || true
        fi
      teardown: |-
        #!/bin/sh
        set -eu
        rm -rf "$VOL_DIR"
