---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coder-edgeone
rules:
  - apiGroups:
      - ""
    resources:
      - services
    resourceNames:
      - coder-gateway-istio
    verbs:
      - get
  - apiGroups:
      - externaldns.k8s.io
    resources:
      - dnsendpoints
    verbs:
      - get
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - cilium.io
    resources:
      - ciliumnetworkpolicies
    verbs:
      - get
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder-edgeone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coder-edgeone
subjects:
  - kind: ServiceAccount
    name: tf-runner
    namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coder-edgeone-crd-reader
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coder-edgeone-crd-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coder-edgeone-crd-reader
subjects:
  - kind: ServiceAccount
    name: tf-runner
    namespace: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coder-edgeone-certificate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coder-edgeone-certificate
rules:
  - apiGroups:
      - infra.contrib.fluxcd.io
    resources:
      - terraforms
    verbs:
      - get
  - apiGroups:
      - externaldns.k8s.io
    resources:
      - dnsendpoints
    verbs:
      - get
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder-edgeone-certificate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coder-edgeone-certificate
subjects:
  - kind: ServiceAccount
    name: coder-edgeone-certificate
    namespace: prod
