apiVersion: v1
kind: Secret
metadata:
  name: coder-edgeone
type: Opaque
stringData:
  TENCENTCLOUD_SECRET_ID: ENC[AES256_GCM,data:WhE9HS1EpuH1gimJaBWxYCe1TJKcH0lN1lak8gyycH5xSjGf,iv:cMQE9ygeSNBlTsFuXsG+chGZqNVGSpk3vD6e8g6cZXk=,tag:QcUPtn3vHcLmuO/4mS6dtw==,type:str]
  TENCENTCLOUD_SECRET_KEY: ENC[AES256_GCM,data:NngRKUqem7KwudhUA2cu6Z2a9q6T2twSJ4nXaTSGFyQ=,iv:aLVqGqqxpEX/WfV7Tqr04oVmgxrXXRQdKMhCDSb6zjY=,tag:CRo2BXqjfsqJBU7Q3cqjSg==,type:str]
  edgeone_zone_id: ENC[AES256_GCM,data:SYzRo3t/aT0O/52J1yGs9CA=,iv:pdsDA2UdoA7S7G7FJ87C6zCjRdrQZPRQH4K/j+QClaI=,tag:icfiqI9eyOdcWGHreUAwOw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbm9jR3YrTWpZNFh1TGd1
        cDFHVHpCNkF4VFc1dWtlRjR3RnVJeXpRckhjCjNSaCsrRFZNc0NuaUF3eGFsbUp6
        N3o2TDlja2Y0dlpQYUcwOVVmWjRGWDgKLS0tIGF3eFlDSy85aUdKM1krNGVBc0M5
        WWFPa0VScEdKZXExc090UDcrdWVYS1EKJG2Cxo6ZpQREkvNu+JdtrvjrY5NmJOA2
        8lVofuTZOBNRoNgnFcBBvboYwjnGhx9/qjaq9yEyiA+TPkgICBpuLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T18:35:23Z"
  mac: ENC[AES256_GCM,data:QnUg9YuG60Fs37QIBIizl2yF1q7XWLJhmTg8k7r+3hjHzGvy/Gj9R18Nez/nz7tvPMoeWHpHPl+2PVsPSZLHbGAKD3wZyIxfrAukTz9IVSlC/8XAd7fBp5qUJcmQbIhlqbMB7pHZgW7lGQ6qIgFJ3cysg056mL/cHnmAYi9SuIw=,iv:Q8Q3DpCONEskvRWE9E2/G5mZjeUYWXu7FcDlNFsgvo4=,tag:PDH7HRklHXV2vgBYh9Ne+g==,type:str]
  version: 3.13.3
