---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: coder
  labels:
    app: coder
spec:
  selector:
    matchLabels:
      app: coder
  endpoints:
    - port: prometheus-http
      path: /metrics
      interval: 30s
