apiVersion: v1
kind: Secret
metadata:
  name: coder-oidc
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:tQcjGwt4vKwXzcN+5tLZKTE+WDW8,iv:fJoQ0Da1wq1ru08RC+ob2AJ/uBbTaufp42gtcjqTVas=,tag:hfFKd/12uQwCRwINqj8E1g==,type:str]
  client-secret: ENC[AES256_GCM,data:dWsQGQQxlE5aLRsG3tXngkTV47Gspd44CBHpD3mZVdI=,iv:yStRF1XXlclwp6a9QxWCY3uWrAlzn98qidS6yS692pE=,tag:cftIT6YcG9OFgZQoMiD1dw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMGoyY08ydi9IQnlHQ1Fs
        eE1JdzVHd09GbGU2ZVB5K0hlaDdoNzZtYTIwCkxaQUVXWUhDOGVXVE05L3dJVmFN
        UWlKalJ1MXhjM3c3L1M1bU9EVGJMRk0KLS0tIGpGNWZlaC9IUWppYlB4NnBqMStC
        UnkxZTM2OU1yVUhqbkRoSjF1UUpNU3MKT6nUnrop39fSTLsGl1A/uohGq9UKwWoB
        P0aG9VyTXlofxwLK6QL/GClKIIS6O7e/UfETTcwRnnwImYrq8Y7odQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T18:15:31Z"
  mac: ENC[AES256_GCM,data:E1gSffVucQTXJJmAN+0YP5j3gEuG486Suoy4k4YovmwPzUA9ZbqAz9IGdF7HaI6KUXli+DHFMTbtVLb5Fu1SGRjILkSVnRgGwYAv8DCYcumqTLHn87gdJPHJfy7gtXV2FXabWQ42gzMEMYXf9epp79VprwfSta2xbT2AIFKUReQ=,iv:sQUiHFUbmd2fQ3+duFlAU4vdUd+p19IjCk4Cbdx0hiE=,tag:PBjD6Fx0sRZOOE4MSthJtQ==,type:str]
  version: 3.13.3
