---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-pg-cluster
spec:
  instances: 3
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: coder-pg-objectstore
        serverName: coder-pg-cluster
  bootstrap:
    initdb:
      owner: coder
      database: coder
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: 16
  storage:
    size: 20Gi
    storageClass: local-path-nocow

  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname

  monitoring:
    enablePodMonitor: true
