---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./base/opentuna.yaml
  - ./base/opentuna-a.yaml
  - ./base/opentuna-c.yaml
  - ./apps.yaml
  - ./vms.yaml
  - ./controllers.yaml
