---
apiVersion: v1
kind: Service
metadata:
  name: proxy-svc
  namespace: egress-system
  labels:
    app: proxy-engine
spec:
  ports:
  - port: 7890
    name: mixed-proxy
    protocol: TCP
    targetPort: 7890
  selector:
    app: proxy-engine
