apiVersion: v1
kind: ConfigMap
metadata:
  name: sing-box-main-config
  namespace: egress-system
data:
  # `route.auto_detect_interface` MUST be `false``, otherwise the proxy will detect the default network interface and bind to it,
  # which will cause network unavailability when service mesh is enabled.
  main.json: |
    {
      "dns": {
        "rules": [
          { "rule_set": ["geosite-cn"], "server": "local" }
        ],
        "servers": [
          { "type": "tls", "server": "one.one.one.one", "detour": "AllNodes", "tag": "remote", "domain_resolver": "local" },
          { "type": "tls", "server": "dot.pub", "detour": "direct", "tag": "local", "domain_resolver": "local-raw" },
          { "type": "local", "detour": "direct", "tag": "local-raw" }
        ],
        "final": "remote",
        "disable_cache": false
      },
      "outbounds": [
          { "type": "direct", "tag": "direct", "domain_resolver": "local" }
      ],
      "inbounds": [
        {
          "listen": "0.0.0.0",
          "listen_port": 7890,
          "tag": "mixed-in",
          "type": "mixed"
        }
      ],
      "route": {
        "auto_detect_interface": false,
        "default_domain_resolver": {
          "server": "local"
        },
        "rules": [
          {
            "action": "resolve",
            "strategy": "prefer_ipv4"
          },
          { "action": "sniff" },
          { "protocol": "dns", "action": "hijack-dns" },
          { "ip_is_private": true, "outbound": "direct" },
          { "rule_set": ["geosite-cn", "geoip-cn"], "outbound": "direct" },
          { "rule_set": ["anthropic", "google-gemini"], "outbound": "UnitedStates" }
        ],
        "final": "AllNodes",
        "rule_set": [
          {
            "tag": "geosite-cn",
            "type": "remote",
            "format": "binary",
            "url": "https://cdn.jsdelivr.net/gh/SagerNet/sing-geosite@rule-set/geosite-cn.srs",
            "download_detour": "AllNodes"
          },
          {
            "tag": "anthropic",
            "type": "remote",
            "format": "binary",
            "url": "https://cdn.jsdelivr.net/gh/SagerNet/sing-geosite@rule-set/geosite-anthropic.srs",
            "download_detour": "AllNodes"
          },
          {
            "tag": "google-gemini",
            "type": "remote",
            "format": "binary",
            "url": "https://cdn.jsdelivr.net/gh/SagerNet/sing-geosite@rule-set/geosite-google-gemini.srs",
            "download_detour": "AllNodes"
          },
          {
            "tag": "geoip-cn",
            "type": "remote",
            "format": "binary",
            "url": "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/srs/cn.srs",
            "download_detour": "AllNodes"
          }
        ]
      }
    }