apiVersion: v1
kind: Secret
metadata:
  name: sub-converter-suburls-secret
  namespace: egress-system
stringData:
  #ENC[AES256_GCM,data:ahAjMdbJ3XahtOw56kTbuw/leqVOJr61lSjLZeS3vpT22g==,iv:hOZDRpzEZU8yuM7JOC789ray95T4uBlMJtqp4Je6hrM=,tag:ElB2yheRFDB0v7bGaX4t+A==,type:comment]
  SUB_URLS: ENC[AES256_GCM,data:eJMfmSdwUrGfcndYoaQVFIW0iJHE3pI+lDSgfEKCcQX5MpaAa55n2zXoRz8LKQ3PWIrm8DJREQkg/jgua3d18dJD+Zz0bjtprnjrRn+n,iv:q/k7IlACZXW8JRFeEubN07f5kYaMDSy5ja4cZpQCYy0=,tag:PafPYXugTWCatUoH+F7WOQ==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UDlRa3JoN1NFQm1WOElY
        QnJnTXRVQXRidFdJVjFQekVLRnM1K0EyV0FjClQ5c0wveE5NTHRxYUIrakdqTlhG
        b0ZLdnVKOE50ZnNiZWM1aXFpeVozN0EKLS0tIHpaeHc2SHpIZjM3OUdCSWk2Y1U4
        Nm1yUlBSMEhhK3lRbmhQenFxYlI0SjQKKDupOqaQgOAGsGLXBh6iL0lFk51LW/Jz
        yQzUDhC0HPIaR27bZLwUxrYKsMJ56Zy9Pxty5UttELY1QVRh8lzLYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T15:43:13Z"
  mac: ENC[AES256_GCM,data:BTwPjtXMsomu6Uf0RfxNxdjhRCUouGe7HP9WsWyOMrrwU36NlcUkDT1PxCGjcqHjQVZGpAj8CZbaHyyGhNvCOB8Di0O+OGDkTbKvDBtOkrXaMwlTsBe4FaGnd46/1sybe/n8wjTyDcX6W3kE69eV5BFl4tHHPZ0jSFB2Z7osguk=,iv:i8JvZvZIA6U2TsBBJeugE4jhREUx6T0X8Q72f0PJBhU=,tag:SnBRdQZwLsFdMCmFGc5yAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
