apiVersion: v1
kind: Secret
metadata:
  name: sub-converter-suburls-secret
  namespace: egress-system
# Separate multiple sub-URLs with comma, and each sub-URL is in the format of "name:url"
# Optional: set NODE_SELECTIONS like
#   HongKong = [ 'HongKong URLTest', '[YZT] 香港1', '[YZT] 香港2' ]
#   UnitedStates = [ 'UnitedStates URLTest', 'My US Node' ]
stringData:
  SUB_URLS: ENC[AES256_GCM,data:Q17XbPI08hV+xQTI8Zq8GYf2COuhT8IH27nwhAW/mxbU0gc2c3Zwj/waAyk6G4EuF5Ey4nUQNhxsQFWF/0/wGLWF7N23onC5b46HXUQM,iv:gduMRmyd3X6GjGZYy3UKn9YJ+w9j+ywLrqD+XAv4DPs=,tag:WgXuK9iM+k5o5e5G56f31w==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOUJqSzlPRHh3K3Jhc3Zo
        cFh4d0xlZ3JsRE03b1ozTnhDMFZRMVNPNG5NClpsOXkyNncycHEzMGR2bGorM3A4
        WHJPSlNoemhkQnpPYXNJQUFtTFpZeUEKLS0tIE5oM1NCekNtSk5XcmtXRi9OMEZX
        dUFFL0JPVFREZ3RwZWpjclRTYjI2STQK5QAmgI+riHAT59kWePl64Rk67E82c8B2
        2XjWTVfqaFlhY8rMuB7iNZDT8X0CteeCbl2jVSpwNCT06fdAuRHbNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T03:02:51Z"
  mac: ENC[AES256_GCM,data:L36QoeIFozOp4/mkagPiOdjYQYTthrnuoFCoJNuXmqvIx5CmouEeWV9RCkuoYv9Fe3x9lgUhLOIwcbqk7WjsC8It9rNiEu/tI13isR8d2GMeC+2yuxycYUgBzIGfFqjs35bJG4De/lIgilL/2udb4ZhpJxxBoxZbUczYvpw4stI=,iv:zEHoe2IzP5XClG8cs5EoaH/8GeLnf6NSJbFYxbwc+DM=,tag:zqB6iMxY4ootTUDMLG7DHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
