apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: failed
  labels:
    app: failed
spec:
  selector:
    matchLabels:
      app: failed
  endpoints:
    - port: "8080"
      path: /metrics
      interval: 20s
