---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opentuna-c
nameSuffix: -c
commonLabels:
  opentuna.isning.moe/scheme: c
resources:
  - ./../../../base/opentuna/
  - ./../../../base/opentuna/scheme-c/
patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: opentuna
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: opentuna-c.local
      - op: replace
        path: /spec/rules/2/backendRefs/0/name
        value: opentuna-cache-frontend
