---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-telemetry
  namespace: flux-system
spec:
  type: oci
  interval: 12h
  url: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts
