---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-opentelemetry-collector
  namespace: monitoring
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts/opentelemetry-collector
  ref:
    tag: "0.150.1@sha256:3cafeed02edec3fd9e357766cb705fa257146ef60c8bf4a7ea1e48eae37caaae"
