---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helm-chart-oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 12h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/oauth2-proxy/charts/oauth2-proxy
  ref:
    tag: "10.4.3"
    digest: "sha256:8628835e87c24230f59942298663eb6544b285ea0fbbd4370a1882143b065c0e"
