apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:HezdXuREujj/KAbmA2KKfSbX2DuQ,iv:ZHfEm/VKhcDqLvTwVQ8htYUfqH9F9wzQlvRVavKgecU=,tag:UXLjNhG3gLuuorRYLMsYqA==,type:str]
  client-secret: ENC[AES256_GCM,data:nXM1TUHibmL28TaFwntxkQz7o1fZ/guZtPo8TT+cqaE=,iv:0tCyF3CIL0G6NT7+J+i629anVgP3+LYajZ+II70cPSw=,tag:yVX7pqUmaEQlGogao9etYg==,type:str]
  #ENC[AES256_GCM,data:YjuQPgYqYMUTBVLHbyrMM8/9e7qcRbHRpteqH/atXLs0+Xt33KydyibgT1N6i8Jh,iv:3Ws+iLEU6tvJivG1YCQlioozjAa6Fd2AUUSGAXTmO3c=,tag:yR9PjMQShVYvdEarN2EHmw==,type:comment]
  cookie-secret: ENC[AES256_GCM,data:TiQbWWWvyDXcQBQJGBqTOdBlgDti4zJL9etbXa4makYWsutejJa1Pdc/X3g=,iv:P9V/a6120ZWFr0ng2EtjAuOXuJt+bTA6SAFJXtsSccQ=,tag:dQ7YqXiuRpGkCylq5VwX+Q==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd2NnZXFtTC9GbUk3bysv
        UzVMZzVScWtoRUx0K010WTRUNjhBdTlQWkc0CkpSZ3JpdkdVRnBTQ0s0SUllOUk4
        MkFZVWdkTTB1WHVkbjg2YjJhRjFwUU0KLS0tIFVPd3Z4TTJIWjZiWUxKZXF3QTl6
        VVJDa2daSkhrREN1NjgzanNNaFpWQzQK2X16qj2s6KTbuBzLFZkABoJnm7ZfXn5s
        xWvAmvStp0e7ZKquRIyYO7LWgTEVr0XC6UWXNQ7ghiMYtwAeX8aTfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T15:19:32Z"
  mac: ENC[AES256_GCM,data:3hED44kDMmV+xJUq+tKCPTvkOH3POlOskOymvORbDma8kO68qT0clyALV93pnKUmfq/gGuxuNA/IBpNHNwyw4L8WvbWb7wEn8l1km0jbez8t5jp2SxXVtle2dTMIxHuTg0sWsda9agTqh9SXNd2QGZpnYYipxOIdmOR0zAvMaJI=,iv:7IWJb6sLUGCwceEFitq5rR0pk4MfNx9YpPaXOCltEyM=,tag:7/y17M1wXKlTYM6ZB2D54g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
