apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:vP+KralIfL4foNVN1ub8Fxrua2uG5RbiftzWG1sTk80=,iv:wE3u6z8vxu6mwTDKKSnGBeAPK8E+2MVh2sHqUNPiNVM=,tag:Ft0bCqgfem86kLifSMG3nw==,type:str]
  #ENC[AES256_GCM,data:8Y8YXMJinsrZQ742tPfcAG+UxW6WbGE/JW/iaF+pQZyZp1p4ZwvXnFfm/1SkYUuU,iv:03e0jVijJnvDdWrRWH0gfZTXNN1dgcDDW2FDAoYlRHk=,tag:mQr2A9QYgVKFKJGekZk9Zw==,type:comment]
  cookie-secret: ENC[AES256_GCM,data:G9BAuHa2a+gmM4OH+74P3RFViL2ZltR89rcYDDN/Qvb8cDn15vCGEW+elkA=,iv:hV9/aYDhdX5OwWbE0k6PzrAKqn+bMnGS7uJRAvQjR70=,tag:LgxQfTp3fes0H3XarMSRYQ==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTk8wV0lDSWc5K09jcWJG
        T0JSbExySDNYVWRkYUVSTFpyZUZacXNkYVJVCmZkZzhqTWtMRVg2UWZBWjR4Vyt3
        WkxvZTVRT1owaUlxaHFLejJpVTg1MnMKLS0tIElrYWR5SC9WN21ybVR4TEdtcXZr
        dVNlL3kxdjNLazZLM0R2YUgveTg4R1UKnnAHhSTraoopfDWkNHkL/WihdUhRPcnr
        PGnm/HdI/zS60x3rEB+9JYLoBZaV15t5QJ0O6mYfrNmTYRpn5Kw3lA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T13:18:40Z"
  mac: ENC[AES256_GCM,data:m9F9QFMoV3qjtPWOA3JECBGkbGD8k2mI4fqb5L+ymN3j8cpf+KZlPjDWeLpfluHEQYuRguv0k+HrE6/l+AGsGqQIxw/JKWlsg3cYQqpj5894Ggi0VjL4/hE/+S4+8x5CsNF34hofWY0l5DvMJ3o1YDtUi8V5ZzMuoCKUwzLOST0=,iv:oGmK8fcqh7sUhvZGBO39b3AE0C/EcOco+sw6sWPtsOk=,tag:N4ZiM2B0trmzNZ6tk70QGA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
