---
apiVersion: application.logto.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: flux-web-credential
  namespace: flux-system
  annotations:
    crossplane.io/paused: 'true'
    crossplane.io/external-name: REPLACE_WITH_EXISTING_FLUX_CLIENT_ID/REPLACE_WITH_EXISTING_SECRET_NAME
spec:
  managementPolicies:
  - Observe
  forProvider:
    name: REPLACE_WITH_EXISTING_SECRET_NAME
    applicationIdRef:
      name: flux-web
      policy:
        resolve: Always
  providerConfigRef:
    name: isning-logto
    kind: ClusterProviderConfig
  writeConnectionSecretToRef:
    name: flux-web-managed-oidc
