---
apiVersion: application.logto.m.crossplane.io/v1alpha1
kind: Application
metadata:
  name: flux-web
  namespace: flux-system
  annotations:
    crossplane.io/external-name: REPLACE_WITH_EXISTING_FLUX_CLIENT_ID
    crossplane.io/paused: 'true'
spec:
  managementPolicies:
  - Observe
  forProvider:
    name: Flux Web
    type: Traditional
    description: ''
    isThirdParty: false
    redirectUris:
    - https://flux.isning.moe/oauth2/callback
    postLogoutRedirectUris: []
    corsAllowedOrigins: []
    oidcClientMetadataExtra: '{"backchannelLogoutSessionRequired":false}'
    customClientMetadataExtra: '{"idTokenTtl":3600,"refreshTokenTtlInDays":14,"alwaysIssueRefreshToken":false,"rotateRefreshToken":true,"allowTokenExchange":false}'
  providerConfigRef:
    name: isning-logto
    kind: ClusterProviderConfig
  writeConnectionSecretToRef:
    name: flux-web-managed-application
