---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: harbor-config
  namespace: harbor
spec:
  interval: 5m
  url: https://github.com/isning/k8s-gitops
  ref:
    branch: main
