kind: Secret
apiVersion: v1
metadata:
  name: harbor-k8s-robot-account-auth
  namespace: harbor
stringData:
  password: ENC[AES256_GCM,data:418TxvIks+yVAAjhMVticCBxaAqgejBSWvr4oeM2cHI=,iv:CDvnKNJnP60poffZTmn84TSPMjZXE4Jl8o0X5+Ln9iI=,tag:mJ9gZvmUBoFTkWpwLe4csg==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYk0rYVhGQjZ5Rk9SeEQ5
        QVQ3d1BmQ3RzK3V5eUx1K21Cald2OUFlQ3hBCkRwMFZQaVhUaEVmcStzT0poMlVE
        cFNPUjdvNnprMjJsRUI2WEpUZlVJWU0KLS0tIGtVRDg2NEljRHRpbXQvenZ2OTRJ
        Qnd0NDVFaldrUFFLRWxCanhyWFFCbXMKsdqQby2tL2wBaue7Tka7acc9jaJLcEJU
        2/dLtyizkhFcjmKFHLDCqYKpLtaWIuPhBjNtwYRER9qcJ3DyAp5ICg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-11T06:27:33Z"
  mac: ENC[AES256_GCM,data:EMxv7fMgbkCir6R+4o2WxeW5gW8MljoU09JQCp4/pkO36wFBUiFkECUJ5d2r8/OHyLkbcSK0Lft/QKB2igU4LhddoIufNDl+8E2OnhC/Ki5N1ApVWybTTL10NFD8q8uSCK5iFZ3fLYnjBw+ZHkOUC35eVeKHucLZZcXlEpdryxw=,iv:JWgE0ChU4jlDtfua14l2xh7KEff6nW+44Z0AB8kjN7Q=,tag:yKywBVpKysRam46tuhA4OA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
