kind: Secret
apiVersion: v1
metadata:
  name: harbor-k8s-robot-account-auth
  namespace: harbor
stringData:
  password: ENC[AES256_GCM,data:kQEzgqoEvX3Dg1QXAKHNL4CnXewyaR3DWaydv0kAi+U=,iv:tthjxRw6jHruMp1j66/hc/W+tKYaBs7/kRSoCYEk/j8=,tag:028XGRwd1FAuMhaZwnGFGw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aGdkQ01HRmZvc1c0V25m
        dFkzZWt6eUdJbW5sSllWUTd0N3dMMEZQVWlVCkVHWU5HRmgrS1lnT3k0WUVZN29C
        SnRoaDRuVlVnYmNLd1MyVVZ5a2szY1EKLS0tIGUveW51Yzh4Nk9ZWkdjYkM3bTY4
        VzY0OUJuK1BFcmczM3Z3UG83Q2c3eTQKnpfNu0PzInG6b9VvXYZgemB3x3zRPnF6
        VjDueKF7PREJ7Wc42oyI264Z9QxI+e5NOf4b8QJEjXaIPoYwzzjTrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T16:29:02Z"
  mac: ENC[AES256_GCM,data:MHCa3lzkvhkLCog8A4k2I29qDe1XJ/HbvEZ3RlmCvQzW524+zX3xlQqfu02iStmwnyEh8J1J6yidDGoBZm20XMcKBWmox7kOUvKul/eTWLjlJYxBtOssPc7wwYz3PMvAmf61hHAhKhuJj2BTxab4LAfcXXHIIZ2q5+YucM6qlVU=,iv:VEH1Acg3UNYkD3Mz/AD58jDP6RSWDPLVP2VG2GLvWE0=,tag:XktNOKUPVYRO5ikideMfFA==,type:str]
  version: 3.13.1
