---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  approvePlan: auto
  path: ./infra/configs/base/harbor/tf
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  vars:
    - name: harbor_username
      value: admin
  varsFrom:
    - kind: Secret
      name: harbor-admin-auth
      varsKeys:
        - HARBOR_ADMIN_PASSWORD:harbor_password
    - kind: Secret
      name: harbor-k8s-robot-account-auth
      varsKeys:
        - password:robot_account_k8s_secret
  retryInterval: 1m
