---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: harbor-proxy-cache
  namespace: harbor
spec:
  interval: 30m
  approvePlan: auto
  path: ./infra/configs/base/harbor/tf
  sourceRef:
    kind: GitRepository
    name: harbor-config
  vars:
    - name: harbor_username
      value: admin
  varsFrom:
    - kind: Secret
      name: harbor-admin-auth
      varsKeys:
        - HARBOR_ADMIN_PASSWORD:harbor_password
    - kind: Secret
      name: harbor-k8s-robot-account-auth
      varsKeys:
        - password:robot_account_k8s_secret
  retryInterval: 1m
  runnerPodTemplate:
    spec:
      env:
        - name: HTTP_PROXY
          value: http://proxy-svc.egress-system.svc.cluster.local:7890
        - name: HTTPS_PROXY
          value: http://proxy-svc.egress-system.svc.cluster.local:7890
        - name: NO_PROXY
          value: 127.0.0.1,localhost,.svc,.cluster.local
