---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gateway-infra.yaml
  - ./gateway-prod.yaml
  - ./gateway-staging.yaml
  - ./oauth2/
  - ./oauth2-proxy-header-transform.yaml
