---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    # From: curl https://raw.githubusercontent.com/longhorn/longhorn/v1.11.2/deploy/longhorn-images.txt
    image-lock/extra-images: >-
      longhornio/backing-image-manager:v1.11.2,
      longhornio/longhorn-engine:v1.11.2,
      longhornio/longhorn-instance-manager:v1.11.2,
      longhornio/longhorn-manager:v1.11.2,
      longhornio/longhorn-share-manager:v1.11.2,
      longhornio/longhorn-ui:v1.11.2,
      longhornio/longhorn-cli:v1.11.2,
      longhornio/csi-attacher:v4.11.0-20260428,
      longhornio/csi-provisioner:v5.3.0-20260428,
      longhornio/csi-resizer:v2.1.0-20260428,
      longhornio/csi-snapshotter:v8.5.0-20260428,
      longhornio/csi-node-driver-registrar:v2.16.0-20260428,
      longhornio/livenessprobe:v2.18.0-20260428,
      longhornio/support-bundle-kit:v0.0.84
spec:
  releaseName: longhorn
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: helm-chart-longhorn
    namespace: controllers
  values:
    image:
      longhorn:
        tag: v1.7.1
    enablePSP: false
    defaultSettings:
      taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule"
      dataEngine: "v1"
      upgradeChecker: "false"
    persistence:
      longhornStorageClass: "longhorn"
    resources:
      manager:
        requests:
          cpu: 10m
          memory: 64Mi
      driver:
        requests:
          cpu: 10m
          memory: 64Mi
    priorityClass:
      systemPriorityClass: system-node-critical
    telemetry:
      enabled: false
    openshift:
      enabled: false