---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dynamic-networks-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynamic-networks-controller
subjects:
  - kind: ServiceAccount
    name: dynamic-networks-controller
    namespace: cluster-network-addons
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dynamic-networks-controller
rules:
  - apiGroups: ["k8s.cni.cncf.io"]
    resources:
      - network-attachment-definitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-networks-controller-config
  namespace: cluster-network-addons
  labels:
    tier: node
    app: multus-dynamic-networks-controller
data:
  dynamic-networks-config.json: |
    {
        "criSocketPath": "/host/run/crio/crio.sock",
        "multusSocketPath": "/host/run/multus/multus.sock"
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dynamic-networks-controller-ds
  namespace: cluster-network-addons
  labels:
    tier: node
    app: dynamic-networks-controller
    name: dynamic-networks-controller
spec:
  selector:
    matchLabels:
      name: dynamic-networks-controller
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: dynamic-networks-controller
        name: dynamic-networks-controller
    spec:
      serviceAccountName: dynamic-networks-controller
      containers:
        - name: dynamic-networks-controller
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: ghcr.io/k8snetworkplumbingwg/multus-dynamic-networks-controller@sha256:2a2bb32c0ea8b232b3dbe81c0323a107e8b05f8cad06704fca2efd0d993a87be
          command: ["/dynamic-networks-controller"]
          args:
            - "-config=/etc/dynamic-networks-controller/dynamic-networks-config.json"
            - "-v=5"
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - --unix-socket
                - /host/run/multus/multus.sock
                - localhost/healthz
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - curl
                - --fail
                - --unix-socket
                - /host/run/multus/multus.sock
                - localhost/healthz
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dynamic-networks-controller-config-dir
              mountPath: /etc/dynamic-networks-controller/
              readOnly: true
            - name: multus-server-socket
              mountPath: /host/run/multus/multus.sock
            - name: cri-socket
              mountPath: /host/run/crio/crio.sock
          terminationMessagePolicy: FallbackToLogsOnError
          imagePullPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
        - name: dynamic-networks-controller-config-dir
          configMap:
            name: dynamic-networks-controller-config
            items:
              - key: dynamic-networks-config.json
                path: dynamic-networks-config.json
        - name: multus-server-socket
          hostPath:
            path: /run/multus/multus.sock
            type: Socket
        - name: cri-socket
          hostPath:
            path: /run/k3s/containerd/containerd.sock
            type: Socket
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynamic-networks-controller
  namespace: cluster-network-addons
