---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-cluster-admin-to-flux-web-admin
  namespace: flux-system
subjects:
  - kind: Group
    name: flux:cluster-admin
    apiGroup: rbac.authorization.k8s.io
# The role is created by flux-operator helm chart.
roleRef:
  kind: ClusterRole
  name: flux-web-admin
  apiGroup: rbac.authorization.k8s.io
