kind: Secret
apiVersion: v1
metadata:
  name: flux-oauth
  namespace: flux-system
stringData:
  client-id: ENC[AES256_GCM,data:AKyWLdLKQfzrpEQT3Ap35d7kwamL,iv:VS+SPqo0GYzGJJS99uGnPZdvFShco5Gauh7u+xbZW04=,tag:3NKzs8BFJqmO7TakXqBftw==,type:str]
  client-secret: ENC[AES256_GCM,data:latQNz4YC40pF5un6f42kWUwJRUIFKxB466huVlrsk0=,iv:gK3Si5k3w50jQtCvsmDo7LWwekkpaJGwvjk6s684p48=,tag:E3Fth1OKfB7UZRcPirB+wg==,type:str]
type: Opaque
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aDFETHN6M25uK3l6ck9x
        RFg1eDRmaXRTVkx6dzdoY05UQ0I2R3pidUhVCm16bGhnSnJ6dlY5YzBtQmVBcjcw
        M2N2WGhPZHFhV3dac25HZGhLQVZqbzAKLS0tIHp2ZC9pUWNZUEJUWU11TWZJTjg5
        VmtlV3dId0dxemd1dWxIcDUwUUYyaW8K/1rX9LGpryLffjmAfJRCJwIvBPEHMiBG
        gh/SjosEVpL9tW8pYwUEA4wSvxky/o8CnZZ+cn0hgkDt0RFJGPbBcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T01:39:25Z"
  mac: ENC[AES256_GCM,data:FOGieamem2JTysE8Y2zcJYj1Cew61+j5vaL5DSIweqtbj4ikQRM1NIp+SFVWccZGdmDOY6XaQxmD3YAAji30LHjOfdWSUbi9rIJ2Ca5/K7fVTOv55D4e4JFEmZTJsjQFvlXZKX7qJd9khu39N7FbX1WcDk3A3MqJR0qoBN9ZV2g=,iv:6lnmGX3XF+c+ePxxDNYvhrr+5i2UkoriHleJqHeHky8=,tag:DqK9nDQbghFEQsgfBPrfvg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
