apiVersion: v1
kind: Secret
metadata:
  name: metapi-secret
type: Opaque
stringData:
  AUTH_TOKEN: ""
  PROXY_TOKEN: ""
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a1Y3M1NHeXZ0cUt2ZGRO
        SGFYSVVvcXVpM3hkcU04VG9ObVVIR1B5ajBRCkxKcTIrd0g3Zi9UWlNVbDBqTnJ1
        bzZJVXU3T2lwYlJMWFVHTW15cVU3bWcKLS0tIDIxbXgwVmhqbkRwZGxZT21keHhI
        TWt5TUFYQkxpdnZiWGx1SVJUbWxLUk0K7rlgefuV2EjZGNtSSD6MssJehlbbMdGz
        NTaO2A86oYLssUvHNcqFmtgcGnEMx4ZMM254LlP2FF6L1pAg5Rj8aQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-20T15:38:28Z"
  mac: ENC[AES256_GCM,data:WDv1dCiimO43WDibchr80o6nAfGdsXFW7wCEG2mgYAUQgVpa6yKheVdSCFCHsGq1XSTFtZJLL7zkgKai8Gq0O9IKVS6QReRVdkr+O6p0xisXpFB61GDSx8IovFfuCqQpYDOHoL3/oaneFfgCMvyqogb/M5dZUNqWQF665yWIjTs=,iv:hCr5WdfYu+0f5QRM4dt+VJ3COqfvMoL6LxLP8YKzcQY=,tag:3jWW9tLwsI5YZOTseeuEFw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
