apiVersion: v1
kind: Secret
metadata:
  name: metapi-secret
type: Opaque
stringData:
  AUTH_TOKEN: ENC[AES256_GCM,data:u2p2gGjeH+WvyITjJl9mMg==,iv:sECTDW00rUEko/lBcpdI2sW8+KXO7ybkdi/zmPYw33o=,tag:n/yT3RPXiVPckqo2d0VOfA==,type:str]
  PROXY_TOKEN: ENC[AES256_GCM,data:Bexsk6lfpoLt6Gm1+lk0kG+LjffC5hxnPfSIRxDFcPlYJ2QwVUDoB3qt5mcrxVs89SdN,iv:9gqvJUfueV3m7TmR+CPKwH0e5Um8lCb6vE9TtmOfuXQ=,tag:MnvMPAythQDpB3+nSHEfgw==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ25EaW92OU14aFZrS1k3
        NmxrVWdxS1lUb0xlUnNOeVcydXZIVENhUXlBCjNpd2hMSXdIdDI2aTlFUnR4NG5B
        YTJZcnpRY1pzZTBhU0VESlA5NTNFN2MKLS0tIFdHZEFUbnBVMkdxY1RsMnpOQjcv
        c29DWVB5Z2ZLT3Jhc1JZTUFnejduWTQK090BU7abyYwmQvTbvDpVlm+pibKsclmB
        Uj4GDJt8BvUHAvi1/u1wO1HziVgzpwEEbax6Xs3/v7W+ktCDmdjfeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-20T15:55:18Z"
  mac: ENC[AES256_GCM,data:64XXtSdylYP5C84ryxBVmFXnnkb5h0Hy9T6MrwyGRfrODohw/Aoa8hkYrNfGZkoDlnxmuCJxth90sUkQTyNP8R9o4HW6uzIx8JlW9zRYLUUAnAUZpu7UoODT9hSx1mhajgoR9X1j2LNgJlZX5H3FMWHdBUdQgIDQBcndJcVP+O4=,iv:/TrWSp5SyXxWcdpo0FNB6ufqI1iCaOnCjd83g/Uy1Jc=,tag:yPFioIZBhRFA3rfAyrhpOw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
