apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metapi
  labels:
    app: metapi
spec:
  serviceName: metapi-headless
  replicas: 1
  selector:
    matchLabels:
      app: metapi
  template:
    metadata:
      labels:
        app: metapi
    spec:
      containers:
      - name: metapi
        image: docker.io/1467078763/metapi:latest@sha256:d29e74b18ce0734555c2088f1f6638e301a7fc01873ff979961ff8a1ac618da8
        ports:
        - name: http
          containerPort: 4000
          protocol: TCP
        env:
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: metapi-secret
              key: AUTH_TOKEN
        - name: PROXY_TOKEN
          valueFrom:
            secretKeyRef:
              name: metapi-secret
              key: PROXY_TOKEN
        - name: TZ
          value: "Asia/Shanghai"
        - name: PORT
          value: "4000"
        - name: DATA_DIR
          value: "/app/data"
        - name: NODE_ENV
          value: "production"
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: data
          mountPath: /app/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
