apiVersion: apps/v1
kind: Deployment
metadata:
  name: astrbot
  labels:
    app: astrbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astrbot
  template:
    metadata:
      labels:
        app: astrbot
    spec:
      containers:
        - name: astrbot
          image: soulter/astrbot:v4.23.3@sha256:aec1e0fdcc2fb9ccd72a8d1b5df168cc88001f383a57dbf64922b4d9af5df99a
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Asia/Shanghai"
          ports:
            - containerPort: 6185
              name: webui
            - containerPort: 6199
              name: qq-ws
            # - containerPort: 6195
            #   name: wecom-wh
            # - containerPort: 6196
            #   name: qq-off-wh
          volumeMounts:
            - name: data
              mountPath: /AstrBot/data
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "50m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: astrbot-data-pvc
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
