apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: astrbot-data-pvc
  labels:
    app: astrbot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard
