# https://fluxcd.io/flux/components/helm/helmreleases/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kiali
  namespace: flux-system
spec:
  type: oci
  interval: 12h
  url: oci://ghcr.io/isning/charts-mirror


