name: test

# Copy from https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/.github/workflows/test.yaml

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@f1acb236137acb1283bf3b6be88110479dfd4f45 # main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@f1acb236137acb1283bf3b6be88110479dfd4f45 # main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@f1acb236137acb1283bf3b6be88110479dfd4f45 # main
      - name: Validate manifests
        run: ./scripts/validate.sh
        env:
          # Set to 'true' to fail CI when schema is missing.
          STRICT_MISSING_SCHEMAS: "false"
