name: test

# Copy from https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/.github/workflows/test.yaml

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@a5fa28dcc7117d391670b3ee1de3a3deb233adb4 # main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@a5fa28dcc7117d391670b3ee1de3a3deb233adb4 # main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@a5fa28dcc7117d391670b3ee1de3a3deb233adb4 # main
      - name: Validate manifests
        run: ./scripts/validate.sh
