---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./request-authentication.yaml
  - ./authz-policy.yaml
  - ./webui-secret.yaml
  - ./onebot-secret.yaml
