---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./request-authentication.yaml
  - ./napcat-ext-auth-policy.yaml
  - ./authz-policy.yaml
  - ./webui-config.yaml
  - ./onebot-secret.yaml
