---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: napcat-ext-auth
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: default-gateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts:
              - napcat.isning.moe
            notPaths:
              - /oauth2/*
