apiVersion: v1
kind: Secret
metadata:
  name: napcat-secret
type: Opaque
stringData:
  account: ENC[AES256_GCM,data:bs2nKIJKDr7TWw==,iv:DeREjndH9ZF9qGV4cDR9YW0hrgkVhzji70f6fi87l3U=,tag:drAn7jhIWfHupjadfmOrbw==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUTdJZHhqOTF6QndraVZi
        WXdIeG0zQVg3TE1RWDJDamdXRWtxYUhYb0cwCnVlNFhPZXZrZFM5TTFWbHNESktX
        ek82OXNQS2tjZjlCNHVGdldUK09PV1kKLS0tIGo5M1A5L2xZUUNSZk9hbmVOV2pu
        bVlROFRqUXBjcTlUL2cvMTVkNVo4RkkK797YtVz45/fQNdW/XWhFbB2IaAtYSSm+
        eHsFJh0Orsj4MXzZE/bYq608PVexpmHehNl0TrNgXme3tRyeSVlCiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T13:27:52Z"
  mac: ENC[AES256_GCM,data:FD/NPHqB7/dLwL0fOcTI/0mT+iZvC+xeCW4rpAz0ESV3lCE1ej8LTxgyykgfnogRdgXxka6CUlNmzH6+xhWoii6EjzmNaVapAwZ/3M1+3aA6V5v2x4cJRRf7B6QQKbNopq3AKdUXt/kfaGavUPjTIAQmO+i1uhS7n3bAAiXUocQ=,iv:BK0iD7nrKeMk2bWwqy6e35vVt/YmZPGKaW2VGQKVeBA=,tag:/SqGZ2s/Ppuyp0DNK6bUHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
