# Looks like:
# {
#   "onebot11_1234567890.json": {
#     "network": {
#       "httpServers": [],
#       "httpClients": [],
#       "websocketServers": [],
#       "websocketClients": [
#         {
#           "name": "AstrBot",
#           "enable": true,
#           "url": "ws://astrbot.prod.svc.cluster.local:6199/ws",
#           "messagePostFormat": "array",
#           "reportSelfMessage": false,
#           "reconnectInterval": 5000,
#           "token": "",
#           "debug": false,
#           "heartInterval": 30000,
#           "reconnectInterval": 30000
#         }
#       ]
#     },
#     "musicSignUrl": "",
#     "enableLocalFile2Url": false,
#     "parseMultMsg": false
#   },
#   "onebot11_9876543210.json": {
#     ...
#   }
# }
apiVersion: v1
kind: Secret
metadata:
  name: napcat-onebot-config
type: Opaque
stringData:
  configs.json: ENC[AES256_GCM,data:VP2Y/JH4oi7lorLs6RNO53uUYBu6KCgieI/sdUZ7V9puomiofqYVkPhzpjdpIfbaBp9GBSUt98efbYWnqN4Y5h59QO7Z4bdlKMMnKqyWYJ9hvid3dm1Y96eAVmdblcp/ykH3X8kWylizbLGLs5qq9IUWcKbGRKc+LDsPFSMwsRwuaCGbUTa7EW9hbxvBOIWaWsGwkDTLFBXM14gekXKNi01eXeRQfFDH+ppc18RLfBsIadJyiXZp5YiyxuCZCJPf+xmYojGAXvNXPxPcnVdcA8F09At1S6a0w2U4Psq8kxtcfpATFgiGgKj4KIFQuPE8Lt/rDXIVWccuLBq/E1F2u6BaxM2Sy0ZtJ3oyrXS1heveo+sexKO7dOw6iXnm0K8lkDm09ALvl0gYvGtkFYLBYfpD6gNA860DOg2Ej4agwgi2s2K8n2o+2NQ1OKZcKiNXZ+EK0AQnC/A3AJEWc1DLMqn5zNFKEf+rB8iVsxirLVL5NxuN3PBIMsr4sBTlHeHDw2f8O6bRYlmm0mm5xVULrW+qAQdZUTkKhyoeNnGfqcXE+U3PT5+wcF1yMOoJzJGNb+ExsFIJiVHDWzrEV7itetsNfwEhnoncZpPVjNMPUoG3HwUbjQHTYa6UtGc5pkE8LHLgzEkB0jPdbwXhL1nEXsmYib7OVbTvGUnFaEG8a9kp04cQLsYjPTrAEEAtLFGpxgh5N4ZgQ8vTTshOdYkDGjdFrobY8TNtQJCdzeBHfFZaM8ZvW8B9LHarhRd4djOG1ViFn4yeBE4o6BOeDMf6X4DursisOBlcbS/LM+TKV6pqyCYBhlozpd9FuXESs9hJSK4rd+YwS0u1OwOCtFM=,iv:2Wp0QSP7KKlGJJfQ7ah+KIsFoKKPUaSMZ7Tn3y0U93o=,tag:9ZRXTKPf5IcESUjlghmbJw==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNzh3L0hmTHlBd0xRbzdD
        LzZoUFVydDhzNDRPWVNYbG9QRW9qNVA4dVNzCnplZVRoKzNNTlZqUFFsaTJUVjhl
        MHBOMmtGN2hxNmJ6ZTl2VlpsanlTMUUKLS0tIHdxamZCVlEyVHdhR1paMkxPWUkv
        Yjh2am5YRlZYdDZYekVpQStQSm1pa0kKCuTM7kZG0jFwiLq+9ahqgLxgR3FyB8fT
        VQJ6hLkRCL9ZVj1RWsvg4fgyIYGEFI5Ix3GGB+n7cdc333zgDcucAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T14:25:00Z"
  mac: ENC[AES256_GCM,data:4bIm4MhnNRdUHZusd1SkBMeFE7mvHWTMAZXew7VDROQK6ZB+dLQweiTWHLVTQP+9yPCH12PFAPf8WodL7TKYl7VLQwQ2a6o2VLe2BoA5dwRLj64JqMcP6PYnDsRxz5TnFXddhgHm4LIhqHGBWTZXvYkMo851QyLymOOyAABv7oQ=,iv:sUTH15UMDvBLf0qLA6V2N5mV5MlEpeC2WKL3oPIRHTc=,tag:EP+zU4IMlOGX9ROv88mwmg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
