apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: napcat-config-pvc
  labels:
    app: napcat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
    limits:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: napcat-qq-pvc
  labels:
    app: napcat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
    limits:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: napcat-machine-id-pvc
  labels:
    app: napcat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ki
    limits:
      storage: 1Ki
