apiVersion: v1
kind: ConfigMap
metadata:
  name: napcat-webui-config
# The webui token is not encrypted intentionally, as the webui is guarded by oauth2 proxy.
data:
  webui.json: |
    {
      "host": "0.0.0.0",
      "port": 6099,
      "token": "NapCat123",
      "loginRate": 3,
      "disableWebUI": false,
      "accessControlMode": "none",
      "ipWhitelist": [],
      "ipBlacklist": [],
      "enableXForwardedFor": true,
    }
