apiVersion: v1
kind: Secret
metadata:
  name: napcat-webui-config
type: Opaque
stringData:
  webui.json: ENC[AES256_GCM,data:4HV+tc+5Ka6AeygI65FYzytBOKg11NdYiwzCTATcRZFrIugRXt1n9lne08BKSm4ble8R1NywqnHABnlOaZ8X0K4mb2gQzypPtHHblE7c8PV/QyqMBw1cK3bWoNE5VaC7hfWHOlVg+JaYSXxrtPZFQ+wSgAjzp7pRj/Zafcz0I8xJlhnfLs07h6K1/I9E8iaYACMR4OjbVBgoTBPFjjdessaxw//4vviD2N8I/YfII09d7A6fUCfdbV1CPAkQjqCkGhPF6uACgg8YB+rs67ztSy/BYAfHgGIvVvRGe3qP63aW8M57wBsJyvfb5/r7IIIM/Ok=,iv:oW5jF56jaFyTeNRENbtatTkS3P0LKWMZz8IhPR2a4ic=,tag:5QRCcYEm+e4Ryh8FljDwNw==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcHZSS0o5UUVKaG41UGlR
        b3V0ZmFTTHNIOTVaQlRLK0pERDBBcVhnN1c0CnJXeEpHNEVHVDZ0VEZhU2lqV0t4
        TFBLdjFMaVl0REVBMnM2NjNWRTFOejgKLS0tIEFIQ1hScFovVGM2UXkvMy80bEc3
        Ny9PcGRSbHpkMEdtNG5rOEY1RDIwaUkK8+vTVJD96WgPy2v6z4uXA0WwTIlXcDKx
        aqfCelvGCTCkwv7D2tH2Zl3uyeoDFwrkiYMP5nljUZZbUKxUd9Q7Ww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T12:58:43Z"
  mac: ENC[AES256_GCM,data:Wloonqs3ZZ/C5YZELAiUUpiAAAcgZD3Vj/IRdXpuT+Hs2myODUngn9fEK44swhprSIcGXJXH6BeavWrMdYbSb7uN61X0MXPVTezYls4PSLt07TshjwaxI883kXiPCmx2PjYBrMC0dFWLcEMOJ6eMRtYu52oBwD0q6CJ7jv540WA=,iv:vYPqXteMsobwU9gm+nkzkTLh1XEvgcYtUgy5ey7vkH8=,tag:XsLHpAmQ6pxFHvqmOWXO2w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
