apiVersion: v1
kind: ConfigMap
metadata:
  name: napcat-webui-config
data:
  webui.json: |
    {
      "host": "0.0.0.0",
      "port": 6099,
      "loginRate": 3,
      "disableWebUI": false,
      "accessControlMode": "none",
      "ipWhitelist": [],
      "ipBlacklist": [],
      "enableXForwardedFor": true,
    }
